# Writes Advanced DSA questions 171-180
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Advanced DSA","topic":"Advanced DSA","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(171, "Basic Binary Search", "easy", "Find a target value in a sorted array using binary search.", "Divide the search range in half each step.", "public class BS {\n    public static void main(String[] args) {\n        int[] arr = {1, 3, 5, 7, 9};\n        int target = 7, l = 0, r = arr.length - 1;\n        while (l <= r) {\n            int m = l + (r - l) / 2;\n            if (arr[m] == target) { System.out.println(m); break; }\n            if (arr[m] < target) l = m + 1;\n            else r = m - 1;\n        }\n    }\n}", ["binary search", "arrays", "divide conquer"], "Compute mid as l + (r-l)/2 to avoid overflow."),
 Q(172, "First Occurrence in Sorted Array", "medium", "Find the first index where a target appears in a sorted array.", "Continue searching left after finding a match.", "public class First {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 2, 2, 3};\n        int target = 2, l = 0, r = arr.length - 1, ans = -1;\n        while (l <= r) {\n            int m = l + (r - l) / 2;\n            if (arr[m] == target) { ans = m; r = m - 1; }\n            else if (arr[m] < target) l = m + 1;\n            else r = m - 1;\n        }\n        System.out.println(ans);\n    }\n}", ["binary search", "first occurrence", "arrays"], "Keep searching left after a match to find the first one."),
 Q(173, "Search in Rotated Sorted Array", "hard", "Find a target in an array that was rotated around a pivot.", "Check which half is sorted and search there.", "public class Rot {\n    public static void main(String[] args) {\n        int[] arr = {4, 5, 6, 7, 0, 1, 2};\n        int target = 0, l = 0, r = arr.length - 1;\n        while (l <= r) {\n            int m = l + (r - l) / 2;\n            if (arr[m] == target) { System.out.println(m); break; }\n            if (arr[l] <= arr[m]) {\n                if (target >= arr[l] && target < arr[m]) r = m - 1;\n                else l = m + 1;\n            } else {\n                if (target > arr[m] && target <= arr[r]) l = m + 1;\n                else r = m - 1;\n            }\n        }\n    }\n}", ["binary search", "rotated", "arrays"], "Determine which half is sorted first."),
 Q(174, "Tree Traversal (Inorder)", "easy", "Print all nodes of a binary tree using inorder traversal.", "Recursively visit left, then node, then right.", "public class Node {\n    int val;\n    Node left, right;\n    Node(int v) { val = v; }\n}\npublic class Main {\n    static void inorder(Node n) {\n        if (n == null) return;\n        inorder(n.left);\n        System.out.println(n.val);\n        inorder(n.right);\n    }\n}", ["trees", "inorder", "recursion"], "Left, root, right is the inorder sequence."),
 Q(175, "Tree Height", "medium", "Find the height of a binary tree.", "Recursively compute the max of left and right heights plus one.", "public class Main {\n    static int height(Node n) {\n        if (n == null) return 0;\n        return 1 + Math.max(height(n.left), height(n.right));\n    }\n}", ["trees", "height", "recursion"], "A null node contributes zero height."),
 Q(176, "BST Search", "easy", "Find a value in a binary search tree.", "Compare the target with the current node and go left or right.", "public class Main {\n    static Node search(Node n, int key) {\n        while (n != null && n.val != key) n = (key < n.val) ? n.left : n.right;\n        return n;\n    }\n}", ["BST", "search", "trees"], "Use the ordering property to skip half the tree each step."),
 Q(177, "BFS Graph Traversal", "medium", "Traverse a graph level by level using a queue.", "Start from a node, enqueue neighbors, and dequeue in order.", "import java.util.*;\npublic class BFS {\n    public static void main(String[] args) {\n        List<List<Integer>> graph = Arrays.asList(Arrays.asList(1, 2), Arrays.asList(0, 3), Arrays.asList(0, 3), Arrays.asList(1, 2));\n        boolean[] visited = new boolean(graph.size()];\n        Queue<Integer> q = new LinkedList<>();\n        q.offer(0);\n        visited[0] = true;\n        while (!q.isEmpty()) {\n            int u = q.poll();\n            System.out.println(u);\n            for (int v : graph.get(u)) if (!visited[v]) { visited[v] = true; q.offer(v); }\n        }\n    }\n}", ["graphs", "BFS", "queue"], "Mark nodes visited to avoid revisiting them."),
 Q(178, "DFS Graph Traversal", "medium", "Traverse a graph depth-first using a stack or recursion.", "Follow one path as far as possible before backtracking.", "import java.util.*;\npublic class DFS {\n    public static void main(String[] args) {\n        List<List<Integer>> graph = Arrays.asList(Arrays.asList(1, 2), Arrays.asList(0, 3), Arrays.asList(0, 3), Arrays.asList(1, 2));\n        boolean[] visited = new boolean(graph.size()];\n        dfs(0, graph, visited);\n    }\n    static void dfs(int u, List<List<Integer>> g, boolean[] v) {\n        v[u] = true;\n        System.out.println(u);\n        for (int w : g.get(u)) if (!v[w]) dfs(w, g, v);\n    }\n}", ["graphs", "DFS", "recursion"], "Recursively visit each unvisited neighbor."),
 Q(179, "Connected Components", "hard", "Count how many separate groups exist in an undirected graph.", "Run BFS or DFS from each unvisited node.", "import java.util.*;\npublic class Components {\n    public static void main(String[] args) {\n        List<List<Integer>> graph = Arrays.asList(Arrays.asList(1), Arrays.asList(0), Arrays.asList(3), Arrays.asList(2));\n        boolean[] visited = new boolean(graph.size()];\n        int count = 0;\n        for (int i = 0; i < graph.size(); i++) {\n            if (!visited[i]) {\n                count++;\n                Queue<Integer> q = new LinkedList<>();\n                q.offer(i);\n                visited[i] = true;\n                while (!q.isEmpty()) {\n                    int u = q.poll();\n                    for (int v : graph.get(u)) if (!visited[v]) { visited[v] = true; q.offer(v); }\n                }\n            }\n        }\n        System.out.println(count);\n    }\n}", ["graphs", "connected components", "BFS"], "Each unvisited node starts a new component."),
 Q(180, "Fibonacci with DP", "easy", "Compute the nth Fibonacci number using memoization.", "Store computed values to avoid recomputation.", "public class Fib {\n    public static void main(String[] args) {\n        int n = 10;\n        int[] dp = new int[n + 1];\n        dp[1] = 1;\n        for (int i = 2; i <= n; i++) dp[i] = dp[i - 1] + dp[i - 2];\n        System.out.println(dp[n]);\n    }\n}", ["DP", "fibonacci", "memoization"], "Build the table from small values upward.")
]
path = os.path.join(BASE, "advancedDsaQuestions.js")
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(arr) + "\n")
print("wrote", len(arr), "questions to advancedDsaQuestions.js")