# Writes Advanced DSA questions 181-190
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Advanced DSA","topic":"Advanced DSA","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(181, "Climbing Stairs DP", "medium", "Count the number of ways to climb n stairs taking 1 or 2 steps at a time.", "Use DP where each step depends on the two previous ones.", "public class Stairs {\n    public static void main(String[] args) {\n        int n = 5;\n        int a = 1, b = 2;\n        for (int i = 3; i <= n; i++) { int c = a + b; a = b; b = c; }\n        System.out.println(n <= 2 ? n : b);\n    }\n}", ["DP", "climbing stairs", "fibonacci"], "The answer for n is the sum of answers for n-1 and n-2."),
 Q(182, "0/1 Knapsack", "hard", "Maximize the total value of items that fit into a weight capacity.", "Use DP where each cell stores the best value for a weight and index.", "public class Knapsack {\n    public static void main(String[] args) {\n        int[] w = {1, 3, 4, 5};\n        int[] v = {1, 4, 5, 7};\n        int cap = 7;\n        int[][] dp = new int[w.length + 1][cap + 1];\n        for (int i = 1; i <= w.length; i++) {\n            for (int j = 1; j <= cap; j++) {\n                if (w[i - 1] <= j) dp[i][j] = Math.max(dp[i - 1][j], v[i - 1] + dp[i - 1][j - w[i - 1]]);\n                else dp[i][j] = dp[i - 1][j];\n            }\n        }\n        System.out.println(dp[w.length][cap]);\n    }\n}", ["DP", "knapsack", "0/1"], "Either take the item or skip it."),
 Q(183, "Longest Common Subsequence", "hard", "Find the length of the longest subsequence shared by two strings.", "Use DP comparing characters of both strings.", "public class LCS {\n    public static void main(String[] args) {\n        String a = \"abcde\", b = \"ace\";\n        int[][] dp = new int[a.length() + 1][b.length() + 1];\n        for (int i = 1; i <= a.length(); i++) {\n            for (int j = 1; j <= b.length(); j++) {\n                if (a.charAt(i - 1) == b.charAt(j - 1)) dp[i][j] = dp[i - 1][j - 1] + 1;\n                else dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);\n            }\n        }\n        System.out.println(dp[a.length()][b.length()]);\n    }\n}", ["DP", "subsequence", "strings"], "Matching characters extend the diagonal, otherwise take the max."),
 Q(184, "Min Heap Operations", "easy", "Insert values and repeatedly extract the smallest one.", "Maintain a heap array and bubble up on insert.", "import java.util.*;\npublic class MinHeap {\n    ArrayList<Integer> h = new ArrayList<>();\n    void push(int v) {\n        h.add(v);\n        int i = h.size() - 1;\n        while (i > 0 && h.get(i) < h.get((i - 1) / 2)) { Collections.swap(h, i, (i - 1) / 2); i = (i - 1) / 2; }\n    }\n    int pop() {\n        int min = h.get(0);\n        h.set(0, h.get(h.size() - 1));\n        h.remove(h.size() - 1);\n        return min;\n    }\n}", ["heap", "min heap", "priority queue"], "Bubble up on insert to keep the smallest on top."),
 Q(185, "Kth Largest Element", "medium", "Find the kth largest element in an unsorted array.", "Sort the array and pick the element at the right index.", "import java.util.Arrays;\npublic class Kth {\n    public static void main(String[] args) {\n        int[] arr = {3, 2, 1, 5, 6, 4};\n        int k = 2;\n        Arrays.sort(arr);\n        System.out.println(arr[arr.length - k]);\n    }\n}", ["heap", "sorting", "kth largest"], "After sorting, the kth largest is at length - k."),
 Q(186, "HashMap Frequency Count", "easy", "Count how many times each value appears using a HashMap.", "Increment the count for each value as you scan.", "import java.util.*;\npublic class Freq {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 2, 3, 3, 3};\n        Map<Integer, Integer> map = new HashMap<>();\n        for (int v : arr) map.put(v, map.getOrDefault(v, 0) + 1);\n        System.out.println(map);\n    }\n}", ["hashing", "frequency", "map"], "getOrDefault avoids null checks."),
 Q(187, "HashSet Duplicate Detection", "easy", "Determine whether an array contains any duplicate value.", "Add each value to a HashSet and check for repeats.", "import java.util.*;\npublic class Dup {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 3, 1};\n        Set<Integer> seen = new HashSet<>();\n        for (int v : arr) {\n            if (seen.contains(v)) { System.out.println(true); return; }\n            seen.add(v);\n        }\n    }\n}", ["hashing", "duplicate", "set"], "A set gives O(1) membership checks."),
 Q(188, "Activity Selection Greedy", "medium", "Select the maximum number of non-overlapping activities.", "Sort by finish time and greedily pick compatible ones.", "import java.util.*;\npublic class Activity {\n    public static void main(String[] args) {\n        int[] start = {1, 3, 0, 5};\n        int[] finish = {2, 4, 6, 7};\n        Integer[] idx = new Integer[start.length];\n        for (int i = 0; i < idx.length; i++) idx[i] = i;\n        Arrays.sort(idx, (a, b) -> finish[a] - finish[b]);\n        int count = 0, last = -1;\n        for (int i : idx) {\n            if (start[i] >= last) { count++; last = finish[i]; }\n        }\n        System.out.println(count);\n    }\n}", ["greedy", "scheduling", "activity selection"], "Always pick the activity that finishes earliest."),
 Q(189, "Merge Intervals", "hard", "Merge overlapping intervals into a list of disjoint intervals.", "Sort by start then merge overlapping ranges.", "import java.util.*;\npublic class Merge {\n    public static void main(String[] args) {\n        int[][] intervals = {{1, 3}, {2, 6}, {8, 10}, {15, 18}};\n        Arrays.sort(intervals, (a, b) -> a[0] - b[0]);\n        List<int[]> result = new ArrayList<>();\n        result.add(intervals[0]);\n        for (int i = 1; i < intervals.length; i++) {\n            int[] last = result.get(result.size() - 1);\n            if (intervals[i][0] <= last[1]) last[1] = Math.max(last[1], intervals[i][1]);\n            else result.add(intervals[i]);\n        }\n        System.out.println(result.size());\n    }\n}", ["greedy", "intervals", "sorting"], "Sort first, then merge overlapping ranges."),
 Q(190, "House Robber DP", "hard", "Maximize the sum of non-adjacent elements in an array.", "Use DP where each decision is to rob or skip the current house.", "public class Robber {\n    public static void main(String[] args) {\n        int[] nums = {2, 7, 9, 3, 1};\n        int a = 0, b = 0;\n        for (int n : nums) { int t = Math.max(a + n, b); a = b; b = t; }\n        System.out.println(b);\n    }\n}", ["DP", "house robber", "subsequence"], "At each house choose the better of robbing or skipping.")
]
path = os.path.join(BASE, "advancedDsaQuestions.js")
with open(path, "r", encoding="utf-8") as f:
    content = f.read()
start = content.index("[")
end = content.rindex("]") + 1
existing = json.loads(content[start:end])
allq = existing + arr
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(allq) + "\n")
print("appended", len(arr), "to advancedDsaQuestions.js, total", len(allq))