# Appends React section to the generator script.
path = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\scripts\generate_data.py"

append = r'''

# 3. React (10 questions) - IDs 21-30
react = [
 {"id":21,"title":"Counter with useState","difficulty":"easy","category":"React","topic":"useState","problem":"Build a counter component with increment, decrement, and reset buttons using React state.","example":{"input":"Click +","output":"Number increases"},"approach":"Use the useState hook to hold the count and update it via buttons.","solution":"function Counter() {\n  const [n, setN] = useState(0);\n  return (\n    <div>\n      <p>{n}</p>\n      <button onClick={() => setN(n + 1)}>+</button>\n      <button onClick={() => setN(n - 1)}>-</button>\n      <button onClick={() => setN(0)}>Reset</button>\n    </div>\n  );\n}","time":"O(1)","space":"O(1)","concepts":["useState","Events","JSX"],"leetcode":None,"hint":"Always use the setter function to update state."},
 {"id":22,"title":"Effect Counter","difficulty":"medium","category":"React","topic":"useEffect","problem":"Update the document title to show the current count whenever it changes.","example":{"input":"Click +","output":"Tab title shows count"},"approach":"Use useEffect with the count in its dependency array to set the title.","solution":"useEffect(() => { document.title = \"Count: \" + n; }, [n]);","time":"O(1)","space":"O(1)","concepts":["useEffect","Side effects","Dependencies"],"leetcode":None,"hint":"An empty dependency array runs the effect only on mount."},
 {"id":23,"title":"Props Greeting","difficulty":"easy","category":"React","topic":"Props","problem":"Create a Greeting component that displays a personalized message passed via props.","example":{"input":"name=\"Alice\"","output":"Hello Alice"},"approach":"Accept a name prop and render it inside JSX.","solution":"function Greeting({ name }) {\n  return <h1>Hello, {name}!</h1>;\n}\n<Greeting name=\"Alice\" />","time":"O(1)","space":"O(1)","concepts":["Props","Components","JSX"],"leetcode":None,"hint":"Props flow from parent to child as read-only."},
 {"id":24,"title":"Conditional Rendering Banner","difficulty":"easy","category":"React","topic":"Conditional rendering","problem":"Show a success or error message depending on a boolean state.","example":{"input":"Toggle state","output":"Different message shown"},"approach":"Use an if/else or ternary inside JSX to choose what to render.","solution":"function Banner() {\n  const [ok, setOk] = useState(true);\n  return ok ? <p>Success</p> : <p>Error</p>;\n}","time":"O(1)","space":"O(1)","concepts":["Conditional","useState","JSX"],"leetcode":None,"hint":"Ternary is the most common inline conditional pattern."},
 {"id":25,"title":"Todo List with State","difficulty":"medium","category":"React","topic":"Lists","problem":"Render a list of todo items from an array stored in state.","example":{"input":"Array of tasks","output":"List of items"},"approach":"Map over the array inside JSX to produce list items.","solution":"function TodoList() {\n  const [tasks, setTasks] = useState([\"A\", \"B\"]);\n  return <ul>{tasks.map((t, i) => <li key={i}>{t}</li>)}</ul>;\n}","time":"O(n)","space":"O(n)","concepts":["useState","Lists","key prop"],"leetcode":None,"hint":"Always provide a key prop when mapping to lists."},
 {"id":26,"title":"Controlled Form","difficulty":"medium","category":"React","topic":"Forms","problem":"Create an input whose value is controlled by React state.","example":{"input":"Typing text","output":"Text appears in input"},"approach":"Bind the input value to state and update state on change.","solution":"function Form() {\n  const [v, setV] = useState(\"\");\n  return <input value={v} onChange={e => setV(e.target.value)} />;\n}","time":"O(1)","space":"O(1)","concepts":["Controlled","Forms","useState"],"leetcode":None,"hint":"Controlled inputs must set value and onChange together."},
 {"id":27,"title":"Fetch Data from API","difficulty":"hard","category":"React","topic":"API fetching","problem":"Load and display a list of posts from a public API using useEffect.","example":{"input":"Component mount","output":"Posts rendered"},"approach":"Call fetch inside useEffect, update state with the response, and handle loading.","solution":"useEffect(() => {\n  fetch(\"https://jsonplaceholder.typicode.com/posts\")\n    .then(r => r.json()).then(setPosts);\n}, []);","time":"O(n)","space":"O(n)","concepts":["useEffect","fetch","Async"],"leetcode":None,"hint":"An empty dependency array fetches only once on mount."},
 {"id":28,"title":"Custom Hook useCounter","difficulty":"hard","category":"React","topic":"Custom hooks","problem":"Extract counter logic into a reusable custom hook.","example":{"input":"Multiple components","output":"Each has its own counter"},"approach":"Move state and handlers into a function starting with use and return them.","solution":"function useCounter(initial = 0) {\n  const [n, setN] = useState(initial);\n  return { n, inc: () => setN(n + 1), dec: () => setN(n - 1) };\n}","time":"O(1)","space":"O(1)","concepts":["Custom hooks","Reuse","useState"],"leetcode":None,"hint":"Hooks must be called in the same order every render."},
 {"id":29,"title":"Theme Toggle with Context","difficulty":"hard","category":"React","topic":"Component communication","problem":"Share a theme between distant components without prop drilling.","example":{"input":"Toggle in header","output":"Theme applied everywhere"},"approach":"Create a context, provide a value, and consume it with useContext.","solution":"const C = createContext();\nfunction Provider({ children }) {\n  const [dark, setDark] = useState(false);\n  return <C.Provider value={{ dark, setDark }}>{children}</C.Provider>;\n}","time":"O(1)","space":"O(1)","concepts":["Context","useContext","Provider"],"leetcode":None,"hint":"Context is ideal for theme, user, and locale sharing."},
 {"id":30,"title":"Search Filter with Debounce","difficulty":"hard","category":"React","topic":"Events","problem":"Delay a search query state update so API calls do not fire on every keystroke.","example":{"input":"Rapid typing","output":"Fewer API requests"},"approach":"Store the raw value in state but debounce the effect that uses it.","solution":"useEffect(() => {\n  const t = setTimeout(() => search(query), 300);\n  return () => clearTimeout(t);\n}, [query]);","time":"O(1)","space":"O(1)","concepts":["useEffect","Debounce","Cleanup"],"leetcode":None,"hint":"Return a cleanup function to cancel the previous timer."}
]
w("reactQuestions.js", react)
print("React done")
'''

with open(path, "a", encoding="utf-8") as f:
    f.write(append)
print("Appended React section")