# Writes Arrays questions 101-110
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Arrays","topic":"Arrays","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(101, "Two Pointers Pair Sum", "medium", "Find if two values in a sorted array add up to a target.", "Use two pointers at both ends moving inward.", "public class TwoPtr {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 3, 4, 5};\n        int target = 9, l = 0, r = arr.length - 1;\n        while (l < r) {\n            int sum = arr[l] + arr[r];\n            if (sum == target) { System.out.println(arr[l] + \" \" + arr[r]); break; }\n            if (sum < target) l++;\n            else r--;\n        }\n    }\n}", ["arrays", "two pointers", "sorted"], "Move the left pointer up to increase the sum."),
 Q(102, "Subarray Maximum Sum", "hard", "Find the maximum sum of any contiguous subarray.", "Use Kadane's algorithm.", "public class Kadane {\n    public static void main(String[] args) {\n        int[] arr = {-2, 1, -3, 4, -1, 2, 1, -5, 4};\n        int max = arr[0], cur = arr[0];\n        for (int i = 1; i < arr.length; i++) {\n            cur = Math.max(arr[i], cur + arr[i]);\n            max = Math.max(max, cur);\n        }\n        System.out.println(max);\n    }\n}", ["arrays", "kadane", "subarray"], "Reset the current sum when it becomes negative."),
 Q(103, "Rotate Array", "hard", "Shift every element to the right by k positions.", "Reverse the array in parts to achieve rotation.", "public class Rotate {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 3, 4, 5};\n        int k = 2, n = arr.length;\n        reverse(arr, 0, n - 1);\n        reverse(arr, 0, k - 1);\n        reverse(arr, k, n - 1);\n        System.out.println(java.util.Arrays.toString(arr));\n    }\n    static void reverse(int[] a, int s, int e) {\n        while (s < e) { int t = a[s]; a[s] = a[e]; a[e] = t; s++; e--; }\n    }\n}", ["arrays", "rotation", "reverse"], "Three reverses give a clean rotation."),
 Q(104, "Merge Two Sorted Arrays", "hard", "Merge two sorted arrays into one sorted array.", "Use three pointers to merge like merge sort.", "public class Merge {\n    public static void main(String[] args) {\n        int[] a = {1, 3, 5};\n        int[] b = {2, 4, 6};\n        int[] c = new int[a.length + b.length];\n        int i = 0, j = 0, k = 0;\n        while (i < a.length && j < b.length) {\n            c[k++] = a[i] < b[j] ? a[i++] : b[j++];\n        }\n        while (i < a.length) c[k++] = a[i++];\n        while (j < b.length) c[k++] = b[j++];\n        System.out.println(java.util.Arrays.toString(c));\n    }\n}", ["arrays", "merge", "two pointers"], "Copy remaining elements after one array is exhausted."),
 Q(105, "Missing Number", "hard", "Find the single missing number in a sequence from 1 to n.", "Use the formula n*(n+1)/2 minus the actual sum.", "public class Missing {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 4, 5};\n        int n = 5;\n        int total = n * (n + 1) / 2;\n        int sum = 0;\n        for (int v : arr) sum += v;\n        System.out.println(total - sum);\n    }\n}", ["arrays", "math", "missing number"], "The difference gives the missing value."),
 Q(106, "Majority Element", "hard", "Find the value that appears more than n/2 times.", "Use the Boyer-Moore voting algorithm.", "public class Majority {\n    public static void main(String[] args) {\n        int[] arr = {3, 2, 3};\n        int cand = 0, count = 0;\n        for (int v : arr) {\n            if (count == 0) cand = v;\n            count += (v == cand) ? 1 : -1;\n        }\n        System.out.println(cand);\n    }\n}", ["arrays", "majority", "voting"], "Cancel out pairs of different values."),
 Q(107, "Best Time to Buy and Sell Stock", "hard", "Maximize profit by buying low and selling high once.", "Track the minimum price and maximum profit.", "public class Stock {\n    public static void main(String[] args) {\n        int[] prices = {7, 1, 5, 3, 6, 4};\n        int min = prices[0], profit = 0;\n        for (int p : prices) {\n            min = Math.min(min, p);\n            profit = Math.max(profit, p - min);\n        }\n        System.out.println(profit);\n    }\n}", ["arrays", "greedy", "stock"], "Update the minimum seen so far each day."),
 Q(108, "Container With Most Water", "hard", "Find two lines that form a container holding the most water.", "Use two pointers at both ends moving inward.", "public class Water {\n    public static void main(String[] args) {\n        int[] h = {1, 8, 6, 2, 5, 4, 8, 3, 7};\n        int l = 0, r = h.length - 1, max = 0;\n        while (l < r) {\n            max = Math.max(max, Math.min(h[l], h[r]) * (r - l));\n            if (h[l] < h[r]) l++;\n            else r--;\n        }\n        System.out.println(max);\n    }\n}", ["arrays", "two pointers", "area"], "Move the shorter line inward to find more area."),
 Q(109, "Product of Array Except Self", "hard", "Return an array where each element is the product of all others.", "Compute prefix and suffix products without division.", "public class Product {\n    public static void main(String[] args) {\n        int[] nums = {1, 2, 3, 4};\n        int n = nums.length;\n        int[] res = new int[n];\n        res[0] = 1;\n        for (int i = 1; i < n; i++) res[i] = res[i - 1] * nums[i - 1];\n        int right = 1;\n        for (int i = n - 1; i >= 0; i--) {\n            res[i] *= right;\n            right *= nums[i];\n        }\n        System.out.println(java.util.Arrays.toString(res));\n    }\n}", ["arrays", "prefix", "suffix"], "Use two passes to avoid division."),
 Q(110, "Search in Rotated Sorted Array", "hard", "Find a target value in an array that was rotated around a pivot.", "Use modified binary search.", "public class RotatedSearch {\n    public static void main(String[] args) {\n        int[] nums = {4, 5, 6, 7, 0, 1, 2};\n        int target = 0, l = 0, r = nums.length - 1;\n        while (l <= r) {\n            int m = l + (r - l) / 2;\n            if (nums[m] == target) { System.out.println(m); break; }\n            if (nums[l] <= nums[m]) {\n                if (target >= nums[l] && target < nums[m]) r = m - 1;\n                else l = m + 1;\n            } else {\n                if (target > nums[m] && target <= nums[r]) l = m + 1;\n                else r = m - 1;\n            }\n        }\n    }\n}", ["arrays", "binary search", "rotated"], "Check which half is sorted first.")
]
path = os.path.join(BASE, "arrayQuestions.js")
with open(path, "r", encoding="utf-8") as f:
    content = f.read()
start = content.index("[")
end = content.rindex("]") + 1
existing = json.loads(content[start:end])
allq = existing + arr
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(allq) + "\n")
print("appended", len(arr), "to arrayQuestions.js, total", len(allq))