# Writes Arrays questions 91-100
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Arrays","topic":"Arrays","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(91, "Maximum Element", "easy", "Find the largest value stored in an array.", "Traverse once and keep track of the maximum.", "public class Max {\n    public static void main(String[] args) {\n        int[] arr = {3, 9, 2, 15, 6};\n        int max = arr[0];\n        for (int i = 1; i < arr.length; i++) {\n            if (arr[i] > max) max = arr[i];\n        }\n        System.out.println(max);\n    }\n}", ["arrays", "traversal", "max"], "Start with the first element as the initial max."),
 Q(92, "Minimum Element", "easy", "Find the smallest value stored in an array.", "Traverse once and keep track of the minimum.", "public class Min {\n    public static void main(String[] args) {\n        int[] arr = {3, 9, 2, 15, 6};\n        int min = arr[0];\n        for (int i = 1; i < arr.length; i++) {\n            if (arr[i] < min) min = arr[i];\n        }\n        System.out.println(min);\n    }\n}", ["arrays", "traversal", "min"], "Start with the first element as the initial min."),
 Q(93, "Reverse Array", "easy", "Reverse the order of elements in an array in place.", "Swap the first with the last, moving inward.", "public class Reverse {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 3, 4, 5};\n        for (int i = 0; i < arr.length / 2; i++) {\n            int t = arr[i];\n            arr[i] = arr[arr.length - 1 - i];\n            arr[arr.length - 1 - i] = t;\n        }\n        System.out.println(java.util.Arrays.toString(arr));\n    }\n}", ["arrays", "swap", "two pointers"], "Only iterate to the middle of the array."),
 Q(94, "Linear Search", "easy", "Find the index of a target value in an array.", "Check each element until the target is found.", "public class Search {\n    public static void main(String[] args) {\n        int[] arr = {5, 3, 8, 1};\n        int target = 8;\n        for (int i = 0; i < arr.length; i++) {\n            if (arr[i] == target) { System.out.println(i); break; }\n        }\n    }\n}", ["arrays", "search", "linear"], "Return -1 if the target is not present."),
 Q(95, "Duplicate Element", "medium", "Find and print any value that appears more than once.", "Use a HashSet to track seen values.", "import java.util.HashSet;\npublic class Dup {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 3, 2, 5};\n        HashSet<Integer> seen = new HashSet<>();\n        for (int v : arr) {\n            if (seen.contains(v)) { System.out.println(v); break; }\n            seen.add(v);\n        }\n    }\n}", ["arrays", "hashset", "duplicate"], "A set helps detect repeats in linear time."),
 Q(96, "Sort Array Ascending", "medium", "Sort an array of integers in ascending order.", "Use Arrays.sort for a quick built-in sort.", "import java.util.Arrays;\npublic class Sort {\n    public static void main(String[] args) {\n        int[] arr = {5, 2, 8, 1};\n        Arrays.sort(arr);\n        System.out.println(Arrays.toString(arr));\n    }\n}", ["arrays", "sorting", "built-in"], "Arrays.sort uses a tuned dual-pivot quicksort."),
 Q(97, "Frequency Count", "medium", "Count how many times each distinct value appears.", "Use a HashMap to accumulate counts.", "import java.util.HashMap;\npublic class Freq {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 2, 3, 3, 3};\n        HashMap<Integer, Integer> map = new HashMap<>();\n        for (int v : arr) map.put(v, map.getOrDefault(v, 0) + 1);\n        System.out.println(map);\n    }\n}", ["arrays", "hashmap", "frequency"], "getOrDefault avoids null checks."),
 Q(98, "Two Sum", "medium", "Find two indices whose values add up to a target.", "Use a HashMap to store value-to-index mappings.", "import java.util.HashMap;\npublic class TwoSum {\n    public static void main(String[] args) {\n        int[] arr = {2, 7, 11, 15};\n        int target = 9;\n        HashMap<Integer, Integer> map = new HashMap<>();\n        for (int i = 0; i < arr.length; i++) {\n            if (map.containsKey(target - arr[i])) {\n                System.out.println(map.get(target - arr[i]) + \" \" + i);\n                break;\n            }\n            map.put(arr[i], i);\n        }\n    }\n}", ["arrays", "hashmap", "two sum"], "Store each value with its index while scanning."),
 Q(99, "Prefix Sum", "medium", "Compute the running sum of an array from left to right.", "Add the current value to the previous running total.", "public class Prefix {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 3, 4};\n        int[] prefix = new int[arr.length];\n        prefix[0] = arr[0];\n        for (int i = 1; i < arr.length; i++) prefix[i] = prefix[i - 1] + arr[i];\n        System.out.println(java.util.Arrays.toString(prefix));\n    }\n}", ["arrays", "prefix sum", "running total"], "Each prefix value is the sum up to that index."),
 Q(100, "Sliding Window Sum", "medium", "Compute the sum of every contiguous subarray of size k.", "Slide a window of fixed size and update the sum.", "public class Window {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 3, 4, 5};\n        int k = 3;\n        int sum = 0;\n        for (int i = 0; i < k; i++) sum += arr[i];\n        System.out.println(sum);\n        for (int i = k; i < arr.length; i++) {\n            sum += arr[i] - arr[i - k];\n            System.out.println(sum);\n        }\n    }\n}", ["arrays", "sliding window", "subarray"], "Add the new element and drop the oldest one.")
]
path = os.path.join(BASE, "arrayQuestions.js")
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(arr) + "\n")
print("wrote", len(arr), "questions to arrayQuestions.js")