# Generator for 200 coding practice questions across 12 data files.
import os
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def w(name, arr):
    path = os.path.join(BASE, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write("export default " + repr(arr).replace("'", '"') + "\n")
    print("wrote", name, len(arr), "questions")

# 1. HTML + CSS (10 questions) - IDs 1-10
htmlCss = [
 {"id":1,"title":"Semantic HTML Structure","difficulty":"easy","category":"HTML/CSS","topic":"Semantic HTML","problem":"Build a complete semantic HTML page structure using the most appropriate elements.","example":{"input":"No input required","output":"A well-structured HTML document"},"approach":"Use semantic elements like header, nav, main, section, article, footer instead of generic divs.","solution":"<!DOCTYPE html>\n<html lang=\"en\">\n<head><meta charset=\"UTF-8\"><title>Semantic Page</title></head>\n<body>\n  <header>\n    <h1>Site Title</h1>\n    <nav><a href=\"#home\">Home</a><a href=\"#about\">About</a></nav>\n  </header>\n  <main>\n    <section id=\"home\"><article><h2>Welcome</h2><p>Hello world.</p></article></section>\n    <section id=\"about\"><article><h2>About</h2><p>About us.</p></article></section>\n  </main>\n  <footer><p>2026 JavaNest</p></footer>\n</body>\n</html>","time":"O(1)","space":"O(1)","concepts":["HTML","Semantic Tags","SEO"],"leetcode":None,"hint":"Think about what each part of the page represents."},
 {"id":2,"title":"CSS Selectors Practice","difficulty":"easy","category":"HTML/CSS","topic":"Selectors","problem":"Write CSS that targets elements using tag, class, id, descendant, and attribute selectors.","example":{"input":"HTML with various elements","output":"Styled elements"},"approach":"Combine different selector types to apply specific styles.","solution":"body { font-family: sans-serif; }\nh1 { color: blue; }\n.header { background: #eee; }\n#main-title { font-size: 2rem; }\ndiv p { line-height: 1.6; }\na[href*=\"java\"] { color: orange; }","time":"O(1)","space":"O(1)","concepts":["CSS","Selectors","Specificity"],"leetcode":None,"hint":"Attribute selector uses [attr=value] syntax."},
 {"id":3,"title":"Form with Validation Styling","difficulty":"medium","category":"HTML/CSS","topic":"Forms","problem":"Create a login form and style valid/invalid input states.","example":{"input":"User fills form","output":"Styled form with feedback"},"approach":"Use :valid and :invalid pseudo-classes plus :focus styles.","solution":"input:invalid { border-color: red; }\ninput:valid { border-color: green; }\ninput:focus { outline: none; box-shadow: 0 0 5px blue; }","time":"O(1)","space":"O(1)","concepts":["CSS","Forms","Pseudo-classes"],"leetcode":None,"hint":":valid and :invalid work on form inputs automatically."},
 {"id":4,"title":"Flexbox Card Layout","difficulty":"medium","category":"HTML/CSS","topic":"Flexbox","problem":"Create a responsive row of equal-width cards using Flexbox.","example":{"input":"Array of card items","output":"Evenly distributed card row"},"approach":"Use display:flex on the container with flex-grow and flex-shrink.","solution":".cards { display: flex; gap: 16px; }\n.card { flex: 1 1 200px; background: #fff; padding: 16px; border-radius: 8px; }","time":"O(1)","space":"O(1)","concepts":["CSS","Flexbox","Responsive"],"leetcode":None,"hint":"flex: 1 means grow and shrink equally."},
 {"id":5,"title":"CSS Grid Gallery","difficulty":"hard","category":"HTML/CSS","topic":"CSS Grid","problem":"Build a photo gallery where items fill rows and auto-fit columns.","example":{"input":"Images array","output":"Grid layout"},"approach":"Use grid-template-columns: repeat(auto-fill, minmax(...)) for responsive grid.","solution":".gallery { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 12px; }\n.gallery img { width: 100%; height: auto; }","time":"O(1)","space":"O(1)","concepts":["CSS","Grid","Responsive"],"leetcode":None,"hint":"auto-fill packs as many columns as fit."},
 {"id":6,"title":"Sticky Header Navigation","difficulty":"medium","category":"HTML/CSS","topic":"Positioning","problem":"Make a navigation bar stick to the top of the viewport when scrolling.","example":{"input":"Long page content","output":"Nav stays visible on scroll"},"approach":"Use position: sticky with top: 0 on the nav element.","solution":"nav { position: sticky; top: 0; background: #fff; z-index: 100; padding: 12px; }","time":"O(1)","space":"O(1)","concepts":["CSS","Positioning","sticky"],"leetcode":None,"hint":"sticky behaves like relative until it hits the top edge."},
 {"id":7,"title":"Two-Column Layout","difficulty":"medium","category":"HTML/CSS","topic":"Layout","problem":"Create a two-column layout with a fixed-width sidebar and fluid main content.","example":{"input":"Sidebar + content","output":"Two-column page"},"approach":"Use flex or grid with a fixed sidebar width and flex main area.","solution":".layout { display: flex; }\n.sidebar { width: 250px; }\n.main { flex: 1; padding: 24px; }","time":"O(1)","space":"O(1)","concepts":["CSS","Layout","Flexbox"],"leetcode":None,"hint":"flex: 1 makes the main area fill remaining space."},
 {"id":8,"title":"Media Query Responsive Text","difficulty":"medium","category":"HTML/CSS","topic":"Responsive Design","problem":"Adjust font sizes and layout for small screens using media queries.","example":{"input":"Different screen widths","output":"Readable text on all devices"},"approach":"Define breakpoints and override sizes for smaller viewports.","solution":"body { font-size: 16px; }\n@media (max-width: 768px) { body { font-size: 14px; } .col { flex-direction: column; } }","time":"O(1)","space":"O(1)","concepts":["CSS","Responsive","Media Queries"],"leetcode":None,"hint":"Use max-width breakpoints to scale down."},
 {"id":9,"title":"Table Styling","difficulty":"easy","category":"HTML/CSS","topic":"Tables","problem":"Style a data table with alternating row colors and hover effects.","example":{"input":"Tabular data","output":"Readable table"},"approach":"Use :nth-child(even) for stripes and :hover for highlight.","solution":"table { border-collapse: collapse; width: 100%; }\ntd, th { padding: 10px; border: 1px solid #ddd; }\ntr:nth-child(even) { background: #f9f9f9; }\ntr:hover { background: #eee; }","time":"O(1)","space":"O(1)","concepts":["CSS","Tables","Pseudo-classes"],"leetcode":None,"hint":"nth-child(even) selects even rows."},
 {"id":10,"title":"CSS Variable Theme Switcher","difficulty":"hard","category":"HTML/CSS","topic":"CSS Variables","problem":"Define CSS custom properties and switch between light and dark themes by toggling a class.","example":{"input":"Theme toggle click","output":"Whole page recolors"},"approach":"Store colors in :root variables and override them in a .dark class.","solution":":root { --bg: #fff; --text: #000; }\n.dark { --bg: #111; --text: #fff; }\nbody { background: var(--bg); color: var(--text); }","time":"O(1)","space":"O(1)","concepts":["CSS","Variables","Theming"],"leetcode":None,"hint":"var() reads a custom property value."}
]
w("htmlCssQuestions.js", htmlCss)
print("HTML+CSS done")

# 2. HTML + CSS + JavaScript (10 questions) - IDs 11-20
frontend = [
 {"id":11,"title":"Counter Widget","difficulty":"easy","category":"JavaScript","topic":"DOM Manipulation","problem":"Create a counter that increments, decrements, and resets a number display.","example":{"input":"Button clicks","output":"Number changes on screen"},"approach":"Select the display element and update its textContent on each button click.","solution":"<!DOCTYPE html>\n<html><body>\n<div id=\"counter\">0</div>\n<button id=\"inc\">+</button>\n<button id=\"dec\">-</button>\n<button id=\"reset\">Reset</button>\n<script>\nlet n = 0;\nconst el = document.getElementById(\"counter\");\ndocument.getElementById(\"inc\").onclick = () => { n++; el.textContent = n; };\ndocument.getElementById(\"dec\").onclick = () => { n--; el.textContent = n; };\ndocument.getElementById(\"reset\").onclick = () => { n = 0; el.textContent = n; };\n</script>\n</body></html>","time":"O(1)","space":"O(1)","concepts":["DOM","Events","textContent"],"leetcode":None,"hint":"Use onclick or addEventListener to attach handlers."},
 {"id":12,"title":"To-Do List","difficulty":"medium","category":"JavaScript","topic":"Dynamic UI","problem":"Build a to-do list that adds, deletes, and toggles completed tasks.","example":{"input":"Task name and add button","output":"List of tasks"},"approach":"Store tasks in an array and re-render the list whenever it changes.","solution":"const tasks = [];\nconst list = document.getElementById(\"list\");\nfunction render() { list.innerHTML = tasks.map((t, i) => \"<li>\" + t + \" <button onclick=deleteTask(\" + i + \")>x</button></li>\").join(\"\"); }\nfunction addTask(v) { tasks.push(v); render(); }\nfunction deleteTask(i) { tasks.splice(i, 1); render(); }","time":"O(n)","space":"O(n)","concepts":["DOM","Array","Re-render"],"leetcode":None,"hint":"Re-render the whole list after each change for simplicity."},
 {"id":13,"title":"Simple Calculator","difficulty":"medium","category":"JavaScript","topic":"Calculator","problem":"Make a calculator that adds, subtracts, multiplies, and divides two numbers.","example":{"input":"5 + 3","output":"8"},"approach":"Read two input values and the chosen operator, then apply the matching operation.","solution":"function calc(a, b, op) {\n  if (op === \"+\") return a + b;\n  if (op === \"-\") return a - b;\n  if (op === \"*\") return a * b;\n  if (op === \"/\") return b !== 0 ? a / b : \"Error\";\n}","time":"O(1)","space":"O(1)","concepts":["Operators","Input","Validation"],"leetcode":None,"hint":"Guard divide by zero before returning."},
 {"id":14,"title":"Modal Dialog","difficulty":"medium","category":"JavaScript","topic":"Modal","problem":"Open and close a modal dialog without reloading the page.","example":{"input":"Open button click","output":"Modal appears"},"approach":"Toggle a CSS class that controls display:none/block on the modal.","solution":"const modal = document.getElementById(\"modal\");\nfunction openModal() { modal.style.display = \"block\"; }\nfunction closeModal() { modal.style.display = \"none\"; }","time":"O(1)","space":"O(1)","concepts":["DOM","Display","Event"],"leetcode":None,"hint":"Use display toggling or a visible class with CSS."},
 {"id":15,"title":"Tabbed Content","difficulty":"medium","category":"JavaScript","topic":"Tabs","problem":"Switch between content panels when a tab is clicked.","example":{"input":"Tab click","output":"Matching panel shows"},"approach":"Hide all panels and show the one linked to the clicked tab.","solution":"document.querySelectorAll(\".tab\").forEach(t => {\n  t.onclick = () => {\n    document.querySelectorAll(\".panel\").forEach(p => p.style.display = \"none\");\n    document.getElementById(t.dataset.tab).style.display = \"block\";\n  };\n});","time":"O(n)","space":"O(1)","concepts":["DOM","data attributes","Event"],"leetcode":None,"hint":"data-* attributes link tabs to panels."},
 {"id":16,"title":"Search and Filter List","difficulty":"medium","category":"JavaScript","topic":"Search/filter","problem":"Filter a list of items as the user types in a search box.","example":{"input":"Typing a letter","output":"Matching items remain"},"approach":"Compare each item text with the search query and hide non-matches.","solution":"input.oninput = () => {\n  const q = input.value.toLowerCase();\n  items.forEach(it => { it.style.display = it.textContent.toLowerCase().includes(q) ? \"\" : \"none\"; });\n};","time":"O(n)","space":"O(1)","concepts":["DOM","Filter","String match"],"leetcode":None,"hint":"toLowerCase ensures case-insensitive matching."},
 {"id":17,"title":"LocalStorage Counter","difficulty":"medium","category":"JavaScript","topic":"LocalStorage","problem":"Persist a counter value so it survives page refresh.","example":{"input":"Refresh page","output":"Count restored"},"approach":"Save the count to localStorage on change and read it back on load.","solution":"let n = parseInt(localStorage.getItem(\"count\")) || 0;\nel.textContent = n;\nbtn.onclick = () => { n++; localStorage.setItem(\"count\", n); el.textContent = n; };","time":"O(1)","space":"O(1)","concepts":["LocalStorage","Persistence","JSON"],"leetcode":None,"hint":"localStorage only stores strings, so parse on read."},
 {"id":18,"title":"Dark/Light Theme Toggle","difficulty":"hard","category":"JavaScript","topic":"Dynamic UI","problem":"Toggle a theme class on the body and remember the choice in localStorage.","example":{"input":"Toggle click","output":"Theme switches"},"approach":"Toggle a class on a root element and persist the current choice.","solution":"const saved = localStorage.getItem(\"theme\");\nif (saved) document.body.classList.add(saved);\nbtn.onclick = () => {\n  document.body.classList.toggle(\"dark\");\n  localStorage.setItem(\"theme\", document.body.classList.contains(\"dark\") ? \"dark\" : \"light\");\n};","time":"O(1)","space":"O(1)","concepts":["DOM","Class Toggle","LocalStorage"],"leetcode":None,"hint":"Read the saved theme on page load to avoid flash."},
 {"id":19,"title":"Event Delegation List","difficulty":"hard","category":"JavaScript","topic":"Events","problem":"Attach a single click handler to a list that works for items added later.","example":{"input":"Click any item","output":"Handler fires"},"approach":"Attach the listener to the parent container and check the target tag.","solution":"list.addEventListener(\"click\", (e) => {\n  if (e.target.tagName === \"LI\") { e.target.classList.toggle(\"done\"); }\n});","time":"O(1)","space":"O(1)","concepts":["Events","Delegation","Bubbling"],"leetcode":None,"hint":"Events bubble up, so the parent sees them."},
 {"id":20,"title":"Form Validation","difficulty":"hard","category":"JavaScript","topic":"Validation","problem":"Validate a registration form and show inline error messages.","example":{"input":"Empty email field","output":"Error message shown"},"approach":"Check each field on submit and display messages next to failures.","solution":"form.onsubmit = (e) => {\n  let ok = true;\n  if (!email.value.includes(\"@\")) { error.textContent = \"Invalid email\"; ok = false; }\n  if (!ok) e.preventDefault();\n  return ok;\n};","time":"O(1)","space":"O(1)","concepts":["Forms","Validation","Prevent Default"],"leetcode":None,"hint":"Call preventDefault when validation fails."}
]
w("frontendQuestions.js", frontend)
print("Frontend done")


# 3. React (10 questions) - IDs 21-30
react = [
 {"id":21,"title":"Counter with useState","difficulty":"easy","category":"React","topic":"useState","problem":"Build a counter component with increment, decrement, and reset buttons using React state.","example":{"input":"Click +","output":"Number increases"},"approach":"Use the useState hook to hold the count and update it via buttons.","solution":"function Counter() {\n  const [n, setN] = useState(0);\n  return (\n    <div>\n      <p>{n}</p>\n      <button onClick={() => setN(n + 1)}>+</button>\n      <button onClick={() => setN(n - 1)}>-</button>\n      <button onClick={() => setN(0)}>Reset</button>\n    </div>\n  );\n}","time":"O(1)","space":"O(1)","concepts":["useState","Events","JSX"],"leetcode":None,"hint":"Always use the setter function to update state."},
 {"id":22,"title":"Effect Counter","difficulty":"medium","category":"React","topic":"useEffect","problem":"Update the document title to show the current count whenever it changes.","example":{"input":"Click +","output":"Tab title shows count"},"approach":"Use useEffect with the count in its dependency array to set the title.","solution":"useEffect(() => { document.title = \"Count: \" + n; }, [n]);","time":"O(1)","space":"O(1)","concepts":["useEffect","Side effects","Dependencies"],"leetcode":None,"hint":"An empty dependency array runs the effect only on mount."},
 {"id":23,"title":"Props Greeting","difficulty":"easy","category":"React","topic":"Props","problem":"Create a Greeting component that displays a personalized message passed via props.","example":{"input":"name=\"Alice\"","output":"Hello Alice"},"approach":"Accept a name prop and render it inside JSX.","solution":"function Greeting({ name }) {\n  return <h1>Hello, {name}!</h1>;\n}\n<Greeting name=\"Alice\" />","time":"O(1)","space":"O(1)","concepts":["Props","Components","JSX"],"leetcode":None,"hint":"Props flow from parent to child as read-only."},
 {"id":24,"title":"Conditional Rendering Banner","difficulty":"easy","category":"React","topic":"Conditional rendering","problem":"Show a success or error message depending on a boolean state.","example":{"input":"Toggle state","output":"Different message shown"},"approach":"Use an if/else or ternary inside JSX to choose what to render.","solution":"function Banner() {\n  const [ok, setOk] = useState(true);\n  return ok ? <p>Success</p> : <p>Error</p>;\n}","time":"O(1)","space":"O(1)","concepts":["Conditional","useState","JSX"],"leetcode":None,"hint":"Ternary is the most common inline conditional pattern."},
 {"id":25,"title":"Todo List with State","difficulty":"medium","category":"React","topic":"Lists","problem":"Render a list of todo items from an array stored in state.","example":{"input":"Array of tasks","output":"List of items"},"approach":"Map over the array inside JSX to produce list items.","solution":"function TodoList() {\n  const [tasks, setTasks] = useState([\"A\", \"B\"]);\n  return <ul>{tasks.map((t, i) => <li key={i}>{t}</li>)}</ul>;\n}","time":"O(n)","space":"O(n)","concepts":["useState","Lists","key prop"],"leetcode":None,"hint":"Always provide a key prop when mapping to lists."},
 {"id":26,"title":"Controlled Form","difficulty":"medium","category":"React","topic":"Forms","problem":"Create an input whose value is controlled by React state.","example":{"input":"Typing text","output":"Text appears in input"},"approach":"Bind the input value to state and update state on change.","solution":"function Form() {\n  const [v, setV] = useState(\"\");\n  return <input value={v} onChange={e => setV(e.target.value)} />;\n}","time":"O(1)","space":"O(1)","concepts":["Controlled","Forms","useState"],"leetcode":None,"hint":"Controlled inputs must set value and onChange together."},
 {"id":27,"title":"Fetch Data from API","difficulty":"hard","category":"React","topic":"API fetching","problem":"Load and display a list of posts from a public API using useEffect.","example":{"input":"Component mount","output":"Posts rendered"},"approach":"Call fetch inside useEffect, update state with the response, and handle loading.","solution":"useEffect(() => {\n  fetch(\"https://jsonplaceholder.typicode.com/posts\")\n    .then(r => r.json()).then(setPosts);\n}, []);","time":"O(n)","space":"O(n)","concepts":["useEffect","fetch","Async"],"leetcode":None,"hint":"An empty dependency array fetches only once on mount."},
 {"id":28,"title":"Custom Hook useCounter","difficulty":"hard","category":"React","topic":"Custom hooks","problem":"Extract counter logic into a reusable custom hook.","example":{"input":"Multiple components","output":"Each has its own counter"},"approach":"Move state and handlers into a function starting with use and return them.","solution":"function useCounter(initial = 0) {\n  const [n, setN] = useState(initial);\n  return { n, inc: () => setN(n + 1), dec: () => setN(n - 1) };\n}","time":"O(1)","space":"O(1)","concepts":["Custom hooks","Reuse","useState"],"leetcode":None,"hint":"Hooks must be called in the same order every render."},
 {"id":29,"title":"Theme Toggle with Context","difficulty":"hard","category":"React","topic":"Component communication","problem":"Share a theme between distant components without prop drilling.","example":{"input":"Toggle in header","output":"Theme applied everywhere"},"approach":"Create a context, provide a value, and consume it with useContext.","solution":"const C = createContext();\nfunction Provider({ children }) {\n  const [dark, setDark] = useState(false);\n  return <C.Provider value={{ dark, setDark }}>{children}</C.Provider>;\n}","time":"O(1)","space":"O(1)","concepts":["Context","useContext","Provider"],"leetcode":None,"hint":"Context is ideal for theme, user, and locale sharing."},
 {"id":30,"title":"Search Filter with Debounce","difficulty":"hard","category":"React","topic":"Events","problem":"Delay a search query state update so API calls do not fire on every keystroke.","example":{"input":"Rapid typing","output":"Fewer API requests"},"approach":"Store the raw value in state but debounce the effect that uses it.","solution":"useEffect(() => {\n  const t = setTimeout(() => search(query), 300);\n  return () => clearTimeout(t);\n}, [query]);","time":"O(1)","space":"O(1)","concepts":["useEffect","Debounce","Cleanup"],"leetcode":None,"hint":"Return a cleanup function to cancel the previous timer."}
]
w("reactQuestions.js", react)
print("React done")

print(" Generator complete\)
