# Writes Java Basic questions 41-50 to javaBasicQuestions.js (appends)
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Java Basic","topic":"Java Basics","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(41, "Nested Loop Star Triangle", "medium", "Print a right-angled triangle of stars with 5 rows.", "Use nested loops where outer controls rows and inner controls columns.", "public class Triangle {\n    public static void main(String[] args) {\n        for (int i = 1; i <= 5; i++) {\n            for (int j = 0; j < i; j++) {\n                System.out.print(\"*\");\n            }\n            System.out.println();\n        }\n    }\n}", ["nested loop", "pattern", "print"], "Outer loop counts rows, inner loop prints stars."),
 Q(42, "Multiplication Table", "medium", "Print the multiplication table of a given number up to 10.", "Multiply the number by each value from 1 to 10.", "public class Table {\n    public static void main(String[] args) {\n        int n = 7;\n        for (int i = 1; i <= 10; i++) {\n            System.out.println(n + \" x \" + i + \" = \" + (n * i));\n        }\n    }\n}", ["loop", "multiplication", "output"], "Use a for loop from 1 to 10."),
 Q(43, "Factorial of a Number", "medium", "Calculate the factorial of a non-negative integer.", "Multiply all numbers from 1 to n together.", "public class Factorial {\n    public static void main(String[] args) {\n        int n = 5;\n        long fact = 1;\n        for (int i = 1; i <= n; i++) {\n            fact *= i;\n        }\n        System.out.println(fact);\n    }\n}", ["loop", "factorial", "multiplication"], "Use long to avoid overflow for larger numbers."),
 Q(44, "Sum of Digits", "medium", "Find the sum of all digits in a given integer.", "Use modulo 10 to get the last digit, then divide by 10.", "public class SumDigits {\n    public static void main(String[] args) {\n        int n = 123;\n        int sum = 0;\n        while (n > 0) {\n            sum += n % 10;\n            n /= 10;\n        }\n        System.out.println(sum);\n    }\n}", ["modulo", "while loop", "digits"], "n % 10 gives the last digit."),
 Q(45, "Reverse a Number", "medium", "Reverse the digits of a given integer.", "Build the reversed number digit by digit.", "public class Reverse {\n    public static void main(String[] args) {\n        int n = 1234;\n        int rev = 0;\n        while (n > 0) {\n            rev = rev * 10 + n % 10;\n            n /= 10;\n        }\n        System.out.println(rev);\n    }\n}", ["modulo", "loop", "number manipulation"], "Multiply rev by 10 and add the last digit."),
 Q(46, "Prime Number Check", "hard", "Determine whether a number is prime.", "Check divisibility from 2 up to the square root of n.", "public class Prime {\n    public static void main(String[] args) {\n        int n = 17;\n        boolean prime = true;\n        for (int i = 2; i * i <= n; i++) {\n            if (n % i == 0) { prime = false; break; }\n        }\n        System.out.println(prime ? \"Prime\" : \"Not Prime\");\n    }\n}", ["loop", "modulo", "prime"], "Only check up to the square root of n."),
 Q(47, "Pyramid Pattern", "hard", "Print a centered pyramid of stars with 5 rows.", "Print spaces then stars, increasing stars per row.", "public class Pyramid {\n    public static void main(String[] args) {\n        int rows = 5;\n        for (int i = 1; i <= rows; i++) {\n            for (int s = 0; s < rows - i; s++) System.out.print(\" \");\n            for (int j = 0; j < 2 * i - 1; j++) System.out.print(\"*\");\n            System.out.println();\n        }\n    }\n}", ["nested loop", "pattern", "spaces"], "Spaces create the centering effect."),
 Q(48, "Fibonacci Sequence", "hard", "Print the first n terms of the Fibonacci sequence.", "Each term is the sum of the previous two terms.", "public class Fib {\n    public static void main(String[] args) {\n        int n = 10, a = 0, b = 1;\n        for (int i = 0; i < n; i++) {\n            System.out.print(a + \" \");\n            int c = a + b;\n            a = b;\n            b = c;\n        }\n    }\n}", ["loop", "fibonacci", "sequence"], "Start with 0 and 1, then sum them."),
 Q(49, "Armstrong Number", "hard", "Check if a number equals the sum of its digits raised to the power of the digit count.", "Count digits, then sum each digit raised to that power.", "public class Armstrong {\n    public static void main(String[] args) {\n        int n = 153, t = n, sum = 0, digits = 0;\n        while (t > 0) { digits++; t /= 10; }\n        t = n;\n        while (t > 0) { sum += Math.pow(t % 10, digits); t /= 10; }\n        System.out.println(sum == n ? \"Armstrong\" : \"Not\");\n    }\n}", ["loop", "math", "digit manipulation"], "Math.pow raises a number to a power."),
 Q(50, "Greatest of Three Numbers", "hard", "Find the maximum among three given numbers.", "Compare the three numbers using nested conditions.", "public class Max3 {\n    public static void main(String[] args) {\n        int a = 12, b = 7, c = 19;\n        int max = a;\n        if (b > max) max = b;\n        if (c > max) max = c;\n        System.out.println(max);\n    }\n}", ["if", "comparison", "max"], "Start with one value and update if a larger one is found."),
]
path = os.path.join(BASE, "javaBasicQuestions.js")
with open(path, "r", encoding="utf-8") as f:
    content = f.read()
start = content.index("[")
end = content.rindex("]") + 1
existing = json.loads(content[start:end])
allq = existing + arr
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(allq) + "\n")
print("appended", len(arr), "to javaBasicQuestions.js, total", len(allq))