# Writes Java Hard questions 81-90
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Java Hard","topic":"Java Hard","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(81, "Hollow Diamond Pattern", "hard", "Print a hollow diamond with only the outline visible.", "Print stars only on the boundary of each row.", "public class HollowDiamond {\n    public static void main(String[] args) {\n        int n = 5;\n        for (int i = 1; i <= n; i++) {\n            for (int s = 0; s < n - i; s++) System.out.print(\" \");\n            for (int j = 0; j < 2 * i - 1; j++) {\n                if (j == 0 || j == 2 * i - 2) System.out.print(\"*\");\n                else System.out.print(\" \");\n            }\n            System.out.println();\n        }\n    }\n}", ["nested loop", "pattern", "hollow diamond"], "Print stars only at the first and last position of each row."),
 Q(82, "Multiple Inheritance via Interfaces", "hard", "Simulate multiple inheritance by implementing two interfaces.", "Implement two interfaces in one class.", "public interface A { void a(); }\npublic interface B { void b(); }\npublic class C implements A, B {\n    public void a() { System.out.println(\"A\"); }\n    public void b() { System.out.println(\"B\"); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new C().a(); new C().b();\n    }\n}", ["interfaces", "multiple inheritance", "OOP"], "Java allows multiple interface implementation."),
 Q(83, "Method Overriding Rules", "hard", "Demonstrate valid and invalid method overriding scenarios.", "Same signature, same or wider access modifier.", "public class Parent {\n    protected void show() { System.out.println(\"Parent\"); }\n}\npublic class Child extends Parent {\n    @Override\n    public void show() { System.out.println(\"Child\"); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new Child().show();\n    }\n}", ["overriding", "access modifier", "rules"], "Cannot reduce visibility in the child class."),
 Q(84, "Encapsulation with Validation", "hard", "Add validation logic inside setters to protect field values.", "Reject invalid values inside the setter.", "public class Student {\n    private int age;\n    public void setAge(int a) {\n        if (a >= 0 && a <= 120) age = a;\n    }\n    public int getAge() { return age; }\n}\npublic class Main {\n    public static void main(String[] args) {\n        Student s = new Student();\n        s.setAge(25);\n        System.out.println(s.getAge());\n    }\n}", ["encapsulation", "validation", "private"], "Setters are the right place for validation logic."),
 Q(85, "Interface Default Methods", "hard", "Use a default method from an interface and override it.", "Declare a default method with the default keyword.", "public interface Logger {\n    default void log(String msg) { System.out.println(\"LOG: \" + msg); }\n}\npublic class ConsoleLogger implements Logger {}\npublic class Main {\n    public static void main(String[] args) {\n        new ConsoleLogger().log(\"Hello\");\n    }\n}", ["interfaces", "default method", "java8"], "Default methods provide backward compatibility."),
 Q(86, "Polymorphism with Interfaces", "hard", "Use an interface reference to call different implementations.", "Declare variables with the interface type.", "public interface Payment {\n    void pay(double amount);\n}\npublic class Cash implements Payment {\n    public void pay(double a) { System.out.println(\"Paid \" + a + \" in cash\"); }\n}\npublic class Card implements Payment {\n    public void pay(double a) { System.out.println(\"Paid \" + a + \" by card\"); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        Payment p = new Card();\n        p.pay(100);\n    }\n}", ["polymorphism", "interfaces", "design"], "The reference type does not decide the method called."),
 Q(87, "Static vs Instance Members", "hard", "Differentiate static and instance members with a demonstration.", "static belongs to class, instance belongs to object.", "public class Counter {\n    static int total = 0;\n    int id;\n    Counter() { id = ++total; }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new Counter(); new Counter();\n        System.out.println(Counter.total);\n    }\n}", ["static", "instance", "memory"], "static variables are shared by all objects."),
 Q(88, "Super Constructor Call", "hard", "Call a parent constructor with arguments using super().", "Pass arguments to super().", "public class Animal {\n    Animal(String name) { System.out.println(\"Animal \" + name); }\n}\npublic class Dog extends Animal {\n    Dog() { super(\"Rex\"); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new Dog();\n    }\n}", ["super", "constructor", "inheritance"], "super(args) must be the first statement."),
 Q(89, "Object Composition Example", "hard", "Build objects that contain references to other objects.", "Declare fields of other class types.", "public class Engine {\n    void start() { System.out.println(\"Engine started\"); }\n}\npublic class Car {\n    Engine engine = new Engine();\n    void start() { engine.start(); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new Car().start();\n    }\n}", ["composition", "OOP", "HAS-A"], "Composition gives a whole-part relationship."),
 Q(90, "Abstract vs Interface Comparison", "hard", "List key differences between abstract classes and interfaces.", "Compare constructors, fields, methods, and inheritance.", "public abstract class A {\n    int x;\n    A() {}\n    abstract void m();\n}\npublic interface B {\n    void n();\n}\npublic class C extends A implements B {\n    void m() {}\n    public void n() {}\n}\npublic class Main {\n    public static void main(String[] args) {\n        new C();\n    }\n}", ["abstraction", "interface", "comparison"], "Interfaces cannot hold state or constructors.")
]
path = os.path.join(BASE, "javaHardQuestions.js")
with open(path, "r", encoding="utf-8") as f:
    content = f.read()
start = content.index("[")
end = content.rindex("]") + 1
existing = json.loads(content[start:end])
allq = existing + arr
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(allq) + "\n")
print("appended", len(arr), "to javaHardQuestions.js, total", len(allq))