# Writes Java Intermediate questions 61-70
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Java Intermediate","topic":"Java Intermediate","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(61, "Inheritance Example", "medium", "Create a parent class and a child class that extends it.", "Use the extends keyword.", "public class Animal {\n    void eat() { System.out.println(\"Eating\"); }\n}\npublic class Dog extends Animal {\n    void bark() { System.out.println(\"Barking\"); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        Dog d = new Dog();\n        d.eat();\n        d.bark();\n    }\n}", ["inheritance", "extends", "OOP"], "Child classes inherit methods from the parent."),
 Q(62, "Super Keyword Usage", "medium", "Access the parent class method from a child class using super.", "Call super.methodName().", "public class Parent {\n    void show() { System.out.println(\"Parent\"); }\n}\npublic class Child extends Parent {\n    void show() { super.show(); System.out.println(\"Child\"); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new Child().show();\n    }\n}", ["super", "inheritance", "method call"], "super lets you call the parent version."),
 Q(63, "Encapsulation with Getters Setters", "medium", "Hide fields and provide controlled access through methods.", "Make fields private and add getter and setter methods.", "public class Box {\n    private int size;\n    public int getSize() { return size; }\n    public void setSize(int s) { if (s > 0) size = s; }\n}\npublic class Main {\n    public static void main(String[] args) {\n        Box b = new Box();\n        b.setSize(10);\n        System.out.println(b.getSize());\n    }\n}", ["encapsulation", "private", "getter setter"], "Private fields cannot be accessed directly from outside."),
 Q(64, "Abstract Class", "hard", "Create an abstract class with an abstract method and concrete subclasses.", "Declare the class and method with the abstract keyword.", "public abstract class Shape {\n    abstract double area();\n}\npublic class Circle extends Shape {\n    double r;\n    Circle(double r) { this.r = r; }\n    double area() { return Math.PI * r * r; }\n}\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println(new Circle(5).area());\n    }\n}", ["abstraction", "abstract class", "OOP"], "Abstract classes cannot be instantiated directly."),
 Q(65, "Interface Implementation", "hard", "Define an interface and implement it in a class.", "Use the implements keyword.", "public interface Walkable {\n    void walk();\n}\npublic class Car implements Walkable {\n    public void walk() { System.out.println(\"Car is moving\"); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new Car().walk();\n    }\n}", ["interfaces", "implements", "contract"], "Interfaces define a contract of methods."),
 Q(66, "Exception Handling", "hard", "Handle a potential error using try catch blocks.", "Wrap risky code in try and catch the exception.", "public class Main {\n    public static void main(String[] args) {\n        try {\n            int n = Integer.parseInt(\"abc\");\n        } catch (NumberFormatException e) {\n            System.out.println(\"Invalid number\");\n        }\n    }\n}", ["exceptions", "try catch", "error handling"], "Catch the specific exception type that can occur."),
 Q(67, "ArrayList Basics", "hard", "Store a dynamic list of strings using ArrayList.", "Use the ArrayList class from java.util.", "import java.util.ArrayList;\npublic class Main {\n    public static void main(String[] args) {\n        ArrayList<String> list = new ArrayList<>();\n        list.add(\"Java\");\n        list.add(\"Python\");\n        System.out.println(list);\n    }\n}", ["collections", "ArrayList", " generics"], "ArrayList grows automatically as you add elements."),
 Q(68, "Method Overriding", "hard", "Override a parent method in a child class with the same signature.", "Use the @Override annotation.", "public class Animal {\n    void sound() { System.out.println(\"Animal sound\"); }\n}\npublic class Dog extends Animal {\n    @Override\n    void sound() { System.out.println(\"Dog barks\"); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new Dog().sound();\n    }\n}", ["overriding", "inheritance", "polymorphism"], "The child version is called at runtime."),
 Q(69, "This vs Super", "hard", "Differentiate between this and super keywords with examples.", "this refers to current object, super refers to parent.", "public class Parent {\n    Parent() { System.out.println(\"Parent\"); }\n}\npublic class Child extends Parent {\n    Child() {\n        super();\n        System.out.println(\"Child\");\n    }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new Child();\n    }\n}", ["this", "super", "constructors"], "super() must be the first statement in a constructor."),
 Q(70, "IS-A vs HAS-A", "hard", "Explain inheritance versus composition with code examples.", "IS-A uses extends, HAS-A uses a field reference.", "public class Engine {\n    void start() { System.out.println(\"Engine started\"); }\n}\npublic class Car {\n    Engine e = new Engine();\n    void drive() { e.start(); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new Car().drive();\n    }\n}", ["inheritance", "composition", "OOP"], "HAS-A creates looser coupling than IS-A.")
]
path = os.path.join(BASE, "javaIntermediateQuestions.js")
with open(path, "r", encoding="utf-8") as f:
    content = f.read()
start = content.index("[")
end = content.rindex("]") + 1
existing = json.loads(content[start:end])
allq = existing + arr
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(allq) + "\n")
print("appended", len(arr), "to javaIntermediateQuestions.js, total", len(allq))