# Writes Java Hard questions 71-80
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Java Hard","topic":"Java Hard","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(71, "Diamond Pattern", "hard", "Print a diamond shape made of stars with 5 rows on each half.", "Print the upper pyramid then the inverted pyramid.", "public class Diamond {\n    public static void main(String[] args) {\n        int n = 5;\n        for (int i = 1; i <= n; i++) {\n            for (int s = 0; s < n - i; s++) System.out.print(\" \");\n            for (int j = 0; j < 2 * i - 1; j++) System.out.print(\"*\");\n            System.out.println();\n        }\n        for (int i = n - 1; i >= 1; i--) {\n            for (int s = 0; s < n - i; s++) System.out.print(\" \");\n            for (int j = 0; j < 2 * i - 1; j++) System.out.print(\"*\");\n            System.out.println();\n        }\n    }\n}", ["nested loop", "pattern", "diamond"], "Two loops: one growing, one shrinking."),
 Q(72, "Hollow Square Pattern", "hard", "Print a hollow square of stars with only the border filled.", "Print stars on edges and spaces inside.", "public class Hollow {\n    public static void main(String[] args) {\n        int n = 5;\n        for (int i = 0; i < n; i++) {\n            for (int j = 0; j < n; j++) {\n                if (i == 0 || i == n - 1 || j == 0 || j == n - 1) System.out.print(\"*\");\n                else System.out.print(\" \");\n            }\n            System.out.println();\n        }\n    }\n}", ["nested loop", "pattern", "hollow"], "Check if the position is on the border."),
 Q(73, "Number Pattern Pyramid", "hard", "Print a pyramid of numbers increasing by one each position.", "Print numbers with proper spacing for alignment.", "public class NumPyramid {\n    public static void main(String[] args) {\n        int n = 5;\n        for (int i = 1; i <= n; i++) {\n            for (int s = 0; s < n - i; s++) System.out.print(\"  \");\n            for (int j = i; j < 2 * i; j++) System.out.print(j + \" \");\n            for (int j = 2 * i - 2; j >= i; j--) System.out.print(j + \" \");\n            System.out.println();\n        }\n    }\n}", ["nested loop", "number pattern", "pyramid"], "Print ascending then descending numbers per row."),
 Q(74, "Kadane Algorithm Maximum Subarray", "hard", "Find the maximum sum of any contiguous subarray.", "Track current sum and reset it when it becomes negative.", "public class Kadane {\n    public static void main(String[] args) {\n        int[] arr = {-2, 1, -3, 4, -1, 2, 1, -5, 4};\n        int max = arr[0], cur = arr[0];\n        for (int i = 1; i < arr.length; i++) {\n            cur = Math.max(arr[i], cur + arr[i]);\n            max = Math.max(max, cur);\n        }\n        System.out.println(max);\n    }\n}", ["arrays", "kadane", "subarray"], "Reset current sum when adding the next element reduces it."),
 Q(75, "Two Sum Pair", "hard", "Find two indices whose values add up to a target sum.", "Use a HashMap to store value-to-index mappings.", "import java.util.HashMap;\npublic class TwoSum {\n    public static void main(String[] args) {\n        int[] arr = {2, 7, 11, 15};\n        int target = 9;\n        HashMap<Integer, Integer> map = new HashMap<>();\n        for (int i = 0; i < arr.length; i++) {\n            if (map.containsKey(target - arr[i])) {\n                System.out.println(map.get(target - arr[i]) + \" \" + i);\n                break;\n            }\n            map.put(arr[i], i);\n        }\n    }\n}", ["arrays", "hashmap", "two sum"], "Store each value with its index as you scan."),
 Q(76, "Polymorphism with Method Overriding", "hard", "Demonstrate runtime polymorphism using a parent reference pointing to a child object.", "Call an overridden method through a parent reference.", "public class Animal {\n    void sound() { System.out.println(\"Animal\"); }\n}\npublic class Dog extends Animal {\n    void sound() { System.out.println(\"Dog\"); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        Animal a = new Dog();\n        a.sound();\n    }\n}", ["polymorphism", "overriding", "runtime"], "The object type decides which method runs."),
 Q(77, "Interface vs Abstract Class", "hard", "Compare when to use an abstract class versus an interface.", "Abstract class for shared state, interface for capability.", "public abstract class Animal {\n    abstract void sound();\n}\npublic interface Swimmable {\n    void swim();\n}\npublic class Duck extends Animal implements Swimmable {\n    void sound() { System.out.println(\"Quack\"); }\n    public void swim() { System.out.println(\"Swimming\"); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new Duck().swim();\n    }\n}", ["abstraction", "interface", "design"], "A class can implement many interfaces but extend one class."),
 Q(78, "Constructor Chaining", "hard", "Call one constructor from another using this().", "Use this() as the first statement.", "public class Chain {\n    Chain() { this(\"Default\"); System.out.println(\"No-arg\"); }\n    Chain(String s) { System.out.println(\"Arg: \" + s); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new Chain();\n    }\n}", ["constructors", "chaining", "this"], "this() delegates to another constructor in the same class."),
 Q(79, "Real World OOP Design", "hard", "Model a simple banking system with account classes and methods.", "Use encapsulation and inheritance for different account types.", "public class Account {\n    private double balance;\n    public Account(double b) { balance = b; }\n    public void deposit(double a) { balance += a; }\n    public void withdraw(double a) { if (a <= balance) balance -= a; }\n    public double getBalance() { return balance; }\n}\npublic class Main {\n    public static void main(String[] args) {\n        Account a = new Account(1000);\n        a.withdraw(200);\n        System.out.println(a.getBalance());\n    }\n}", ["OOP", "encapsulation", "design"], "Keep balance private and expose controlled methods."),
 Q(80, "String Buffer vs Builder", "hard", "Explain the difference and show a concatenation example.", "StringBuilder is not thread-safe, StringBuffer is.", "public class Main {\n    public static void main(String[] args) {\n        StringBuilder sb = new StringBuilder(\"Hello\");\n        sb.append(\" World\");\n        System.out.println(sb.toString());\n    }\n}", ["strings", "StringBuilder", "performance"], "Use StringBuilder for single-threaded concatenation.")
]
path = os.path.join(BASE, "javaHardQuestions.js")
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(arr) + "\n")
print("wrote", len(arr), "questions to javaHardQuestions.js")