# Writes Java Basic questions 31-40 to javaBasicQuestions.js
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Java Basic","topic":"Java Basics","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(31, "Hello World", "easy", "Print Hello World to the console.", "Use System.out.println.", "public class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println(\"Hello World\");\n    }\n}", ["Java", "main", "Output"], "Every Java program needs a main method."),
 Q(32, "Variable Assignment", "easy", "Declare and assign an integer variable then print it.", "Use int keyword and = operator.", "public class VarDemo {\n    public static void main(String[] args) {\n        int age = 25;\n        System.out.println(age);\n    }\n}", ["Variables", "Assignment", "int"], "Use the = operator to assign a value."),
 Q(33, "String Input with Scanner", "easy", "Read a line of text from the user and print it.", "Use Scanner with nextLine().", "import java.util.Scanner;\npublic class ScanDemo {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String name = sc.nextLine();\n        System.out.println(\"Hello \" + name);\n    }\n}", ["Scanner", "Input", "String"], "Remember to import java.util.Scanner."),
 Q(34, "If Else Grade Check", "easy", "Print Pass if a score is 40 or above, otherwise print Fail.", "Use an if else statement.", "public class Grade {\n    public static void main(String[] args) {\n        int score = 75;\n        if (score >= 40) {\n            System.out.println(\"Pass\");\n        } else {\n            System.out.println(\"Fail\");\n        }\n    }\n}", ["if", "else", "Condition"], ">= means greater than or equal to."),
 Q(35, "Switch Day of Week", "easy", "Print the day name when given a number 1 to 7.", "Use a switch statement.", "public class Day {\n    public static void main(String[] args) {\n        int d = 3;\n        switch (d) {\n            case 1: System.out.println(\"Monday\"); break;\n            case 2: System.out.println(\"Tuesday\"); break;\n            case 3: System.out.println(\"Wednesday\"); break;\n            default: System.out.println(\"Other\");\n        }\n    }\n}", ["switch", "case", "break"], "Each case needs a break statement."),
 Q(36, "For Loop Sum", "easy", "Add numbers from 1 to 5 and print the total.", "Use a for loop.", "public class Sum {\n    public static void main(String[] args) {\n        int sum = 0;\n        for (int i = 1; i <= 5; i++) {\n            sum += i;\n        }\n        System.out.println(sum);\n    }\n}", ["for loop", "sum", "iteration"], "sum += i is the same as sum = sum + i."),
 Q(37, "While Loop Countdown", "easy", "Print numbers from 5 down to 1.", "Use a while loop.", "public class CountDown {\n    public static void main(String[] args) {\n        int i = 5;\n        while (i > 0) {\n            System.out.println(i);\n            i--;\n        }\n    }\n}", ["while loop", "decrement"], "i-- reduces i by 1 each time."),
 Q(38, "Do While Menu", "easy", "Show a menu at least once even if the condition is false initially.", "Use do while loop.", "public class Menu {\n    public static void main(String[] args) {\n        int choice;\n        do {\n            System.out.println(\"1. Exit\");\n            choice = 1;\n        } while (choice != 1);\n    }\n}", ["do while", "loop"], "do while runs the body first, then checks."),
 Q(39, "Method Addition", "easy", "Create a method that returns the sum of two numbers.", "Define a method with parameters and return.", "public class Add {\n    static int add(int a, int b) {\n        return a + b;\n    }\n    public static void main(String[] args) {\n        System.out.println(add(10, 20));\n    }\n}", ["method", "return", "parameters"], "Use return to send a value back from a method."),
 Q(40, "Even Odd Check", "easy", "Tell whether a number is even or odd.", "Use modulo operator %.", "public class EvenOdd {\n    public static void main(String[] args) {\n        int n = 14;\n        if (n % 2 == 0) {\n            System.out.println(\"Even\");\n        } else {\n            System.out.println(\"Odd\");\n        }\n    }\n}", ["modulo", "if", "condition"], "A number is even when n % 2 equals 0."),
]
path = os.path.join(BASE, "javaBasicQuestions.js")
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(arr) + "\n")
print("wrote", len(arr), "questions to javaBasicQuestions.js")