# Writes Java Intermediate questions 51-60
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Java Intermediate","topic":"Java Intermediate","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(51, "Array Max Element", "easy", "Find the largest value stored in an integer array.", "Traverse the array and keep track of the maximum.", "public class Max {\n    public static void main(String[] args) {\n        int[] arr = {3, 9, 2, 15, 6};\n        int max = arr[0];\n        for (int i = 1; i < arr.length; i++) {\n            if (arr[i] > max) max = arr[i];\n        }\n        System.out.println(max);\n    }\n}", ["arrays", "traversal", "max"], "Start with the first element as the initial max."),
 Q(52, "String Reverse", "easy", "Reverse a string and print the result.", "Build a new string by iterating from the end.", "public class Rev {\n    public static void main(String[] args) {\n        String s = \"hello\";\n        String r = \"\";\n        for (int i = s.length() - 1; i >= 0; i--) {\n            r += s.charAt(i);\n        }\n        System.out.println(r);\n    }\n}", ["strings", "loop", "charAt"], "charAt(i) returns the character at index i."),
 Q(53, "Array Copy", "easy", "Copy all elements of one array into another array of the same size.", "Loop through the first array and assign values to the second.", "public class Copy {\n    public static void main(String[] args) {\n        int[] a = {1, 2, 3};\n        int[] b = new int[a.length];\n        for (int i = 0; i < a.length; i++) b[i] = a[i];\n        System.out.println(java.util.Arrays.toString(b));\n    }\n}", ["arrays", "copy", "loop"], "Use a for loop to transfer each element."),
 Q(54, "Palindrome Check", "medium", "Check whether a string reads the same forwards and backwards.", "Compare characters from both ends moving inward.", "public class Palindrome {\n    public static void main(String[] args) {\n        String s = \"level\";\n        boolean ok = true;\n        for (int i = 0; i < s.length() / 2; i++) {\n            if (s.charAt(i) != s.charAt(s.length() - 1 - i)) { ok = false; break; }\n        }\n        System.out.println(ok ? \"Palindrome\" : \"Not\");\n    }\n}", ["strings", "loop", "palindrome"], "Only iterate up to the middle of the string."),
 Q(55, "Count Vowels", "medium", "Count how many vowels appear in a given string.", "Check each character against the set of vowels.", "public class Vowels {\n    public static void main(String[] args) {\n        String s = \"hello world\";\n        int c = 0;\n        for (char ch : s.toCharArray()) {\n            if (\"aeiouAEIOU\".indexOf(ch) >= 0) c++;\n        }\n        System.out.println(c);\n    }\n}", ["strings", "loop", "vowels"], "Use a for-each loop over the characters."),
 Q(56, "Method Overloading Example", "medium", "Create multiple methods with the same name but different parameters.", "Change the number or type of parameters.", "public class Overload {\n    static int add(int a, int b) { return a + b; }\n    static int add(int a, int b, int c) { return a + b + c; }\n    public static void main(String[] args) {\n        System.out.println(add(1, 2));\n        System.out.println(add(1, 2, 3));\n    }\n}", ["methods", "overloading", "polymorphism"], "The compiler picks the matching method by parameters."),
 Q(57, "Class and Object", "medium", "Create a class with fields and methods, then instantiate an object.", "Define a class and use the new keyword.", "public class Car {\n    String model;\n    Car(String m) { model = m; }\n    void drive() { System.out.println(model + \" is driving\"); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        Car c = new Car(\"Civic\");\n        c.drive();\n    }\n}", ["OOP", "class", "object"], "Objects are created from classes with new."),
 Q(58, "Constructor Overloading", "medium", "Provide multiple constructors that differ in their parameter lists.", "Declare several constructors in the same class.", "public class Student {\n    String name;\n    int age;\n    Student() { name = \"Unknown\"; age = 0; }\n    Student(String n) { name = n; age = 0; }\n    Student(String n, int a) { name = n; age = a; }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new Student(\"Alice\", 20);\n    }\n}", ["constructors", "overloading", "OOP"], "Constructors run automatically when an object is created."),
 Q(59, "Static Variable", "medium", "Share a single value across all objects of a class using static.", "Declare the field with the static keyword.", "public class Counter {\n    static int count = 0;\n    Counter() { count++; }\n    public static void main(String[] args) {\n        new Counter(); new Counter();\n        System.out.println(Counter.count);\n    }\n}", ["static", "class variable", "memory"], "static fields belong to the class, not individual objects."),
 Q(60, "This Keyword", "medium", "Use the this keyword to refer to the current object within a method.", "Use this to distinguish fields from parameters.", "public class Person {\n    String name;\n    Person(String name) { this.name = name; }\n    void greet() { System.out.println(\"Hi \" + this.name); }\n}\npublic class Main {\n    public static void main(String[] args) {\n        new Person(\"Bob\").greet();\n    }\n}", ["this", "OOP", "references"], "this helps avoid shadowing when parameter names match fields.")
]
path = os.path.join(BASE, "javaIntermediateQuestions.js")
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(arr) + "\n")
print("wrote", len(arr), "questions to javaIntermediateQuestions.js")