# Writes Linked List questions 131-140
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Linked List","topic":"Linked List","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(131, "Create and Traverse Linked List", "easy", "Build a singly linked list and print all its values.", "Define a node class and link nodes together.", "public class Node {\n    int data;\n    Node next;\n    Node(int d) { data = d; }\n}\npublic class Main {\n    public static void main(String[] args) {\n        Node head = new Node(1);\n        head.next = new Node(2);\n        head.next.next = new Node(3);\n        for (Node c = head; c != null; c = c.next) System.out.println(c.data);\n    }\n}", ["linked list", "node", "traversal"], "Traverse using a current pointer until it becomes null."),
 Q(132, "Insert at End", "easy", "Add a new value at the tail of a linked list.", "Walk to the last node and link the new node.", "public class Main {\n    static Node insertEnd(Node head, int val) {\n        Node node = new Node(val);\n        if (head == null) return node;\n        Node c = head;\n        while (c.next != null) c = c.next;\n        c.next = node;\n        return head;\n    }\n}", ["linked list", "insert", "tail"], "Handle the empty list case first."),
 Q(133, "Delete a Node", "easy", "Remove the first node that holds a given value.", "Skip the node by relinking its predecessor.", "public class Main {\n    static Node delete(Node head, int key) {\n        if (head != null && head.data == key) return head.next;\n        Node c = head;\n        while (c != null && c.next != null) {\n            if (c.next.data == key) { c.next = c.next.next; break; }\n            c = c.next;\n        }\n        return head;\n    }\n}", ["linked list", "delete", "pointer"], "Relink the previous node to the next node."),
 Q(134, "Search in Linked List", "easy", "Find whether a value exists in a linked list.", "Walk the list and compare each node.", "public class Main {\n    static boolean contains(Node head, int key) {\n        for (Node c = head; c != null; c = c.next) if (c.data == key) return true;\n        return false;\n    }\n}", ["linked list", "search", "traversal"], "Return false if the pointer reaches the end."),
 Q(135, "Find Middle Node", "medium", "Find the node in the middle of a linked list.", "Use fast and slow pointers moving at different speeds.", "public class Main {\n    static int middle(Node head) {\n        Node slow = head, fast = head;\n        while (fast != null && fast.next != null) { slow = slow.next; fast = fast.next.next; }\n        return slow.data;\n    }\n}", ["linked list", "two pointers", "fast slow"], "Slow moves one step, fast moves two steps."),
 Q(136, "Reverse Linked List", "medium", "Reverse the direction of all next pointers.", "Iteratively flip each link.", "public class Main {\n    static Node reverse(Node head) {\n        Node prev = null, cur = head;\n        while (cur != null) {\n            Node next = cur.next;\n            cur.next = prev;\n            prev = cur;\n            cur = next;\n        }\n        return prev;\n    }\n}", ["linked list", "reverse", "pointer"], "Keep a prev pointer and flip each link."),
 Q(137, "Detect Cycle", "hard", "Determine if a linked list contains a cycle.", "Use fast and slow pointers and check for meeting.", "public class Main {\n    static boolean hasCycle(Node head) {\n        Node slow = head, fast = head;\n        while (fast != null && fast.next != null) {\n            slow = slow.next;\n            fast = fast.next.next;\n            if (slow == fast) return true;\n        }\n        return false;\n    }\n}", ["linked list", "cycle", "fast slow"], "If fast catches slow, a cycle exists."),
 Q(138, "Remove Duplicates", "medium", "Remove duplicate values from a sorted linked list.", "Skip nodes whose value matches the previous kept value.", "public class Main {\n    static Node removeDup(Node head) {\n        Node c = head;\n        while (c != null && c.next != null) {\n            if (c.data == c.next.data) c.next = c.next.next;\n            else c = c.next;\n        }\n        return head;\n    }\n}", ["linked list", "duplicate", "sorted"], "Compare each node with its next node."),
 Q(139, "Merge Two Sorted Lists", "hard", "Merge two sorted linked lists into one sorted list.", "Pick the smaller node at each step.", "public class Main {\n    static Node merge(Node a, Node b) {\n        Node dummy = new Node(0), c = dummy;\n        while (a != null && b != null) {\n            if (a.data < b.data) { c.next = a; a = a.next; }\n            else { c.next = b; b = b.next; }\n            c = c.next;\n        }\n        c.next = (a != null) ? a : b;\n        return dummy.next;\n    }\n}", ["linked list", "merge", "two pointers"], "Use a dummy node to simplify edge cases."),
 Q(140, "Find Nth Node from End", "hard", "Find the value of the nth node counting from the end.", "Use two pointers spaced n apart.", "public class Main {\n    static Integer nthFromEnd(Node head, int n) {\n        if (head == null || n <= 0) return null;\n        Node fast = head, slow = head;\n        for (int i = 0; i < n; i++) {\n            if (fast == null) return null;\n            fast = fast.next;\n        }\n        while (fast != null) { slow = slow.next; fast = fast.next; }\n        return slow.data;\n    }\n}", ["linked list", "two pointers", "nth"], "Advance the first pointer by n steps, then move both.")
]
path = os.path.join(BASE, "linkedListQuestions.js")
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(arr) + "\n")
print("wrote", len(arr), "questions to linkedListQuestions.js")