# Writes Linked List questions 141-150
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Linked List","topic":"Linked List","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(141, "Intersection of Two Lists", "hard", "Find the node where two linked lists meet.", "Align the starts then walk both lists together.", "public class Main {\n    static Node intersect(Node a, Node b) {\n        int la = len(a), lb = len(b);\n        while (la > lb) { a = a.next; la--; }\n        while (lb > la) { b = b.next; lb--; }\n        while (a != b) { a = a.next; b = b.next; }\n        return a;\n    }\n    static int len(Node h) { int n = 0; while (h != null) { n++; h = h.next; } return n; }\n}", ["linked list", "intersection", "two pointers"], "Equalize lengths first, then walk in parallel."),
 Q(142, "Add Two Numbers as Lists", "hard", "Add two numbers stored as reversed linked lists.", "Sum digits with carry and build a new list.", "public class Main {\n    static Node add(Node a, Node b) {\n        Node dummy = new Node(0), c = dummy;\n        int carry = 0;\n        while (a != null || b != null || carry > 0) {\n            int sum = carry + (a != null ? a.data : 0) + (b != null ? b.data : 0);\n            c.next = new Node(sum % 10);\n            c = c.next;\n            carry = sum / 10;\n            if (a != null) a = a.next;\n            if (b != null) b = b.next;\n        }\n        return dummy.next;\n    }\n}", ["linked list", "addition", "carry"], "Process both lists and handle the final carry."),
 Q(143, "Copy List with Random Pointers", "hard", "Deep copy a linked list where each node has a random pointer.", "Interleave copies then separate them.", "public class RNode {\n    int data;\n    RNode next, random;\n    RNode(int d) { data = d; }\n}\npublic class Main {\n    static RNode copy(RNode head) {\n        if (head == null) return null;\n        RNode c = head;\n        while (c != null) { RNode next = c.next; c.next = new RNode(c.data); c.next.next = next; c = next; }\n        c = head;\n        while (c != null) { if (c.random != null) c.next.random = c.random.next; c = c.next.next; }\n        RNode newHead = head.next;\n        c = head;\n        while (c != null) { RNode copy = c.next; c.next = copy.next; copy.next = copy.next != null ? copy.next.next : null; c = c.next; }\n        return newHead;\n    }\n}", ["linked list", "deep copy", "random"], "Interleave, set random pointers, then separate."),
 Q(144, "Doubly Linked List Insert", "easy", "Insert a value into a sorted doubly linked list.", "Update both next and prev pointers.", "public class DNode {\n    int data;\n    DNode prev, next;\n    DNode(int d) { data = d; }\n}\npublic class Main {\n    static void insert(DNode head, int val) {\n        DNode node = new DNode(val);\n        if (head == null || head.data >= val) { node.next = head; if (head != null) head.prev = node; return; }\n        DNode c = head;\n        while (c.next != null && c.next.data < val) c = c.next;\n        node.next = c.next;\n        node.prev = c;\n        if (c.next != null) c.next.prev = node;\n        c.next = node;\n    }\n}", ["doubly linked list", "insert", "sorted"], "Update both prev and next of affected nodes."),
 Q(145, "Doubly Linked List Delete", "easy", "Remove a node from a doubly linked list.", "Relink neighbors skipping the node.", "public class Main {\n    static void delete(DNode node) {\n        if (node.prev != null) node.prev.next = node.next;\n        if (node.next != null) node.next.prev = node.prev;\n    }\n}", ["doubly linked list", "delete", "pointers"], "Fix both the prev and next links."),
 Q(146, "Circular Linked List Insert", "medium", "Insert a value into a circular linked list maintaining the loop.", "Find the insertion point around the circle.", "public class Main {\n    static Node insertCircular(Node head, int val) {\n        Node node = new Node(val);\n        if (head == null) { node.next = node; return node; }\n        Node c = head;\n        while (c.next != head && c.next.data < val) c = c.next;\n        node.next = c.next;\n        c.next = node;\n        return head;\n    }\n}", ["circular linked list", "insert", "loop"], "Stop when the next pointer wraps back to head."),
 Q(147, "Detect Loop in Linked List", "hard", "Find the start node of a cycle if one exists.", "Find the meeting point then walk from head and meeting point.", "public class Main {\n    static Node detectCycle(Node head) {\n        Node slow = head, fast = head;\n        while (fast != null && fast.next != null) {\n            slow = slow.next;\n            fast = fast.next.next;\n            if (slow == fast) break;\n        }\n        if (fast == null || fast.next == null) return null;\n        slow = head;\n        while (slow != fast) { slow = slow.next; fast = fast.next; }\n        return slow;\n    }\n}", ["linked list", "cycle", "floyd"], "After the meeting point, reset one pointer to head."),
 Q(148, "Swap Nodes in Pairs", "hard", "Swap every two adjacent nodes in a linked list.", "Relink nodes in groups of two.", "public class Main {\n    static Node swapPairs(Node head) {\n        Node dummy = new Node(0), prev = dummy;\n        dummy.next = head;\n        while (prev.next != null && prev.next.next != null) {\n            Node first = prev.next, second = first.next;\n            prev.next = second;\n            first.next = second.next;\n            second.next = first;\n            prev = first;\n        }\n        return dummy.next;\n    }\n}", ["linked list", "swap", "pairs"], "Use a dummy node to simplify the head swap."),
 Q(149, "Rotate Linked List", "hard", "Rotate a linked list to the right by k positions.", "Find the tail, cut the list, and reattach.", "public class Main {\n    static Node rotateRight(Node head, int k) {\n        if (head == null) return head;\n        int n = 1;\n        Node tail = head;\n        while (tail.next != null) { tail = tail.next; n++; }\n        k %= n;\n        if (k == 0) return head;\n        Node c = head;\n        for (int i = 0; i < n - k - 1; i++) c = c.next;\n        Node newHead = c.next;\n        c.next = null;\n        tail.next = head;\n        return newHead;\n    }\n}", ["linked list", "rotation", "tail"], "Connect the tail to the old head."),
 Q(150, "Flatten Multilevel List", "hard", "Flatten a multilevel linked list into a single level list.", "Depth-first flatten and reconnect tail pointers.", "public class Main {\n    static Node flatten(Node head) {\n        Node c = head;\n        while (c != null) {\n            if (c.child != null) {\n                Node next = c.next;\n                Node tail = c.child;\n                while (tail.next != null) tail = tail.next;\n                c.next = c.child;\n                c.child = null;\n                tail.next = next;\n                c = tail;\n            } else c = c.next;\n        }\n        return head;\n    }\n}", ["linked list", "flatten", "multilevel"], "Splice the child list in place of the original next.")
]
path = os.path.join(BASE, "linkedListQuestions.js")
with open(path, "r", encoding="utf-8") as f:
    content = f.read()
start = content.index("[")
end = content.rindex("]") + 1
existing = json.loads(content[start:end])
allq = existing + arr
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(allq) + "\n")
print("appended", len(arr), "to linkedListQuestions.js, total", len(allq))