# Writes Mixed Interview questions 191-200
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint, leetcode=None):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Interview","topic":"Mixed Interview","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":leetcode,"hint":hint}

arr = [
 Q(191, "Reverse an Array In Place", "easy", "Reverse the elements of an array without using extra space.", "Swap the first element with the last moving inward.", "public class Rev {\n    public static void main(String[] args) {\n        int[] arr = {1, 2, 3, 4, 5};\n        for (int i = 0; i < arr.length / 2; i++) {\n            int t = arr[i];\n            arr[i] = arr[arr.length - 1 - i];\n            arr[arr.length - 1 - i] = t;\n        }\n        System.out.println(java.util.Arrays.toString(arr));\n    }\n}", ["arrays", "swap", "two pointers"], "Only iterate to the middle of the array."),
 Q(192, "Check Anagram", "easy", "Determine if two strings are anagrams of each other.", "Compare sorted versions or frequency counts.", "import java.util.Arrays;\npublic class Ana {\n    public static void main(String[] args) {\n        String a = \"listen\", b = \"silent\";\n        char[] x = a.toCharArray();\n        char[] y = b.toCharArray();\n        Arrays.sort(x);\n        Arrays.sort(y);\n        System.out.println(Arrays.equals(x, y));\n    }\n}", ["strings", "anagram", "sorting"], "Sorting both strings makes comparison easy."),
 Q(193, "Find Middle of Linked List", "easy", "Find the middle node of a singly linked list.", "Use slow and fast pointers moving at different speeds.", "public class Main {\n    static int middle(Node head) {\n        Node slow = head, fast = head;\n        while (fast != null && fast.next != null) { slow = slow.next; fast = fast.next.next; }\n        return slow.data;\n    }\n}", ["linked list", "two pointers", "fast slow"], "Slow moves one step, fast moves two steps."),
 Q(194, "Factorial Using Recursion", "easy", "Compute the factorial of a number using a recursive method.", "Multiply n by the factorial of n-1 until reaching the base case.", "public class Fact {\n    public static void main(String[] args) {\n        System.out.println(fact(5));\n    }\n    static int fact(int n) {\n        if (n <= 1) return 1;\n        return n * fact(n - 1);\n    }\n}", ["recursion", "factorial", "math"], "Base case stops the recursion at n equals 1."),
 Q(195, "Linear Search", "easy", "Find the index of a target value by checking each element.", "Scan the array and return the first matching index.", "public class Search {\n    public static void main(String[] args) {\n        int[] arr = {5, 3, 8, 1};\n        int target = 8;\n        for (int i = 0; i < arr.length; i++) {\n            if (arr[i] == target) { System.out.println(i); break; }\n        }\n    }\n}", ["arrays", "search", "linear"], "Return -1 if the target is not present."),
 Q(196, "Bubble Sort Array", "medium", "Sort an array using the bubble sort algorithm.", "Repeatedly swap adjacent out-of-order elements.", "public class Bubble {\n    public static void main(String[] args) {\n        int[] arr = {5, 2, 8, 1};\n        for (int i = 0; i < arr.length - 1; i++) {\n            for (int j = 0; j < arr.length - 1 - i; j++) {\n                if (arr[j] > arr[j + 1]) { int t = arr[j]; arr[j] = arr[j + 1]; arr[j + 1] = t; }\n            }\n        }\n        System.out.println(java.util.Arrays.toString(arr));\n    }\n}", ["sorting", "bubble sort", "arrays"], "Each pass bubbles the largest element to the end."),
 Q(197, "String Builder Concatenation", "medium", "Efficiently build a long string using StringBuilder.", "Append parts to a StringBuilder then convert to a string.", "public class Build {\n    public static void main(String[] args) {\n        StringBuilder sb = new StringBuilder();\n        for (int i = 0; i < 1000; i++) sb.append(\"Hello \");\n        System.out.println(sb.toString());\n    }\n}", ["strings", "StringBuilder", "performance"], "StringBuilder avoids creating many intermediate strings."),
 Q(198, "Reverse a String", "easy", "Reverse a string and print the result.", "Build a new string by iterating from the last character.", "public class Rev {\n    public static void main(String[] args) {\n        String s = \"hello\";\n        String r = \"\";\n        for (int i = s.length() - 1; i >= 0; i--) r += s.charAt(i);\n        System.out.println(r);\n    }\n}", ["strings", "reverse", "loop"], "charAt(i) returns the character at index i."),
 Q(199, "Stack Push Pop Sequence", "medium", "Simulate push and pop operations and print the resulting stack.", "Use a list to represent the stack and operate on its end.", "import java.util.*;\npublic class StackSim {\n    public static void main(String[] args) {\n        Deque<Integer> s = new ArrayDeque<>();\n        s.push(1);\n        s.push(2);\n        System.out.println(s.pop());\n        s.push(3);\n        while (!s.isEmpty()) System.out.println(s.pop());\n    }\n}", ["stack", "simulation", "deque"], "Push adds to the top, pop removes from the top."),
 Q(200, "Two Sum Pair Check", "easy", "Check if any two values in an array add up to a target.", "Use a HashSet to store seen values and look for the complement.", "import java.util.*;\npublic class TwoSum {\n    public static void main(String[] args) {\n        int[] arr = {2, 7, 11, 15};\n        int target = 9;\n        Set<Integer> seen = new HashSet<>();\n        for (int v : arr) {\n            if (seen.contains(target - v)) { System.out.println(true); break; }\n            seen.add(v);\n        }\n    }\n}", ["arrays", "two sum", "hashset"], "Store each value and check for its complement.")
]
path = os.path.join(BASE, "mixedInterviewQuestions.js")
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(arr) + "\n")
print("wrote", len(arr), "questions to mixedInterviewQuestions.js")