# Regenerates frontendQuestions.js with proper JSON formatting
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, category, topic, problem, approach, solution, concepts, hint, leetcode=None):
    return {"id":id,"title":title,"difficulty":difficulty,"category":category,"topic":topic,"problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":leetcode,"hint":hint}

arr = [
 Q(11, "Counter Widget", "easy", "JavaScript", "DOM Manipulation", "Create a counter that increments, decrements, and resets a number display.", "Select the display element and update its textContent on each button click.", '<!DOCTYPE html>\n<html><body>\n<div id="counter">0</div>\n<button id="inc">+</button>\n<button id="dec">-</button>\n<button id="reset">Reset</button>\n<script>\nlet n = 0;\nconst el = document.getElementById("counter");\ndocument.getElementById("inc").onclick = () => { n++; el.textContent = n; };\ndocument.getElementById("dec").onclick = () => { n--; el.textContent = n; };\ndocument.getElementById("reset").onclick = () => { n = 0; el.textContent = n; };\n</script>\n</body></html>', ["DOM", "Events", "textContent"], "Use onclick or addEventListener to attach handlers."),
 Q(12, "To-Do List", "medium", "JavaScript", "Dynamic UI", "Build a to-do list that adds, deletes, and toggles completed tasks.", "Store tasks in an array and re-render the list whenever it changes.", "const tasks = [];\nconst list = document.getElementById(\"list\");\nfunction render() { list.innerHTML = tasks.map((t, i) => \"<li>\" + t + \" <button onclick=deleteTask(\" + i + \")>x</button></li>\").join(\"\"); }\nfunction addTask(v) { tasks.push(v); render(); }\nfunction deleteTask(i) { tasks.splice(i, 1); render(); }", ["DOM", "Array", "Re-render"], "Re-render the whole list after each change for simplicity."),
 Q(13, "Simple Calculator", "medium", "JavaScript", "Calculator", "Make a calculator that adds, subtracts, multiplies, and divides two numbers.", "Read two input values and the chosen operator, then apply the matching operation.", "function calc(a, b, op) {\n  if (op === \"+\") return a + b;\n  if (op === \"-\") return a - b;\n  if (op === \"*\") return a * b;\n  if (op === \"/\") return b !== 0 ? a / b : \"Error\";\n}", ["Operators", "Input", "Validation"], "Guard divide by zero before returning."),
 Q(14, "Modal Dialog", "medium", "JavaScript", "Modal", "Open and close a modal dialog without reloading the page.", "Toggle a CSS class that controls display:none/block on the modal.", "const modal = document.getElementById(\"modal\");\nfunction openModal() { modal.style.display = \"block\"; }\nfunction closeModal() { modal.style.display = \"none\"; }", ["DOM", "Display", "Event"], "Use display toggling or a visible class with CSS."),
 Q(15, "Tabbed Content", "medium", "JavaScript", "Tabs", "Switch between content panels when a tab is clicked.", "Hide all panels and show the one linked to the clicked tab.", "document.querySelectorAll(\".tab\").forEach(t => {\n  t.onclick = () => {\n    document.querySelectorAll(\".panel\").forEach(p => p.style.display = \"none\");\n    document.getElementById(t.dataset.tab).style.display = \"block\";\n  };\n});", ["DOM", "data attributes", "Event"], "data-* attributes link tabs to panels."),
 Q(16, "Search and Filter List", "medium", "JavaScript", "Search/filter", "Filter a list of items as the user types in a search box.", "Compare each item text with the search query and hide non-matches.", "input.oninput = () => {\n  const q = input.value.toLowerCase();\n  items.forEach(it => { it.style.display = it.textContent.toLowerCase().includes(q) ? \"\" : \"none\"; });\n};", ["DOM", "Filter", "String match"], "toLowerCase ensures case-insensitive matching."),
 Q(17, "LocalStorage Counter", "medium", "JavaScript", "LocalStorage", "Persist a counter value so it survives page refresh.", "Save the count to localStorage on change and read it back on load.", "let n = parseInt(localStorage.getItem(\"count\")) || 0;\nel.textContent = n;\nbtn.onclick = () => { n++; localStorage.setItem(\"count\", n); el.textContent = n; };", ["LocalStorage", "Persistence", "JSON"], "localStorage only stores strings, so parse on read."),
 Q(18, "Dark/Light Theme Toggle", "hard", "JavaScript", "Dynamic UI", "Toggle a theme class on the body and remember the choice in localStorage.", "Toggle a class on a root element and persist the current choice.", "const saved = localStorage.getItem(\"theme\");\nif (saved) document.body.classList.add(saved);\nbtn.onclick = () => {\n  document.body.classList.toggle(\"dark\");\n  localStorage.setItem(\"theme\", document.body.classList.contains(\"dark\") ? \"dark\" : \"light\");\n};", ["DOM", "Class Toggle", "LocalStorage"], "Read the saved theme on page load to avoid flash."),
 Q(19, "Event Delegation List", "hard", "JavaScript", "Events", "Attach a single click handler to a list that works for items added later.", "Attach the listener to the parent container and check the target tag.", "list.addEventListener(\"click\", (e) => {\n  if (e.target.tagName === \"LI\") { e.target.classList.toggle(\"done\"); }\n});", ["Events", "Delegation", "Bubbling"], "Events bubble up, so the parent sees them."),
 Q(20, "Form Validation", "hard", "JavaScript", "Validation", "Validate a registration form and show inline error messages.", "Check each field on submit and display messages next to failures.", "form.onsubmit = (e) => {\n  let ok = true;\n  if (!email.value.includes(\"@\")) { error.textContent = \"Invalid email\"; ok = false; }\n  if (!ok) e.preventDefault();\n  return ok;\n};", ["Forms", "Validation", "Prevent Default"], "Call preventDefault when validation fails.")
]
path = os.path.join(BASE, "frontendQuestions.js")
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(arr) + "\n")
print("wrote", len(arr), "questions to frontendQuestions.js")