# Regenerates htmlCssQuestions.js with proper JSON formatting
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, category, topic, problem, approach, solution, concepts, hint, leetcode=None):
    return {"id":id,"title":title,"difficulty":difficulty,"category":category,"topic":topic,"problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":leetcode,"hint":hint}

arr = [
 Q(1, "Semantic HTML Structure", "easy", "HTML/CSS", "Semantic HTML", "Build a complete semantic HTML page structure using the most appropriate elements.", "Use semantic elements like header, nav, main, section, article, footer instead of generic divs.", '<!DOCTYPE html>\n<html lang="en">\n<head><meta charset="UTF-8"><title>Semantic Page</title></head>\n<body>\n  <header>\n    <h1>Site Title</h1>\n    <nav><a href="#home">Home</a><a href="#about">About</a></nav>\n  </header>\n  <main>\n    <section id="home"><article><h2>Welcome</h2><p>Hello world.</p></article></section>\n    <section id="about"><article><h2>About</h2><p>About us.</p></article></section>\n  </main>\n  <footer><p>2026 JavaNest</p></footer>\n</body>\n</html>', ["HTML", "Semantic Tags", "SEO"], "Think about what each part of the page represents."),
 Q(2, "CSS Selectors Practice", "easy", "HTML/CSS", "Selectors", "Write CSS that targets elements using tag, class, id, descendant, and attribute selectors.", "Combine different selector types to apply specific styles.", "body { font-family: sans-serif; }\nh1 { color: blue; }\n.header { background: #eee; }\n#main-title { font-size: 2rem; }\ndiv p { line-height: 1.6; }\na[href*=\"java\"] { color: orange; }", ["CSS", "Selectors", "Specificity"], "Attribute selector uses [attr=value] syntax."),
 Q(3, "Form with Validation Styling", "medium", "HTML/CSS", "Forms", "Create a login form and style valid/invalid input states.", "Use :valid and :invalid pseudo-classes plus :focus styles.", "input:invalid { border-color: red; }\ninput:valid { border-color: green; }\ninput:focus { outline: none; box-shadow: 0 0 5px blue; }", ["CSS", "Forms", "Pseudo-classes"], ":valid and :invalid work on form inputs automatically."),
 Q(4, "Flexbox Card Layout", "medium", "HTML/CSS", "Flexbox", "Create a responsive row of equal-width cards using Flexbox.", "Use display:flex on the container with flex-grow and flex-shrink.", ".cards { display: flex; gap: 16px; }\n.card { flex: 1 1 200px; background: #fff; padding: 16px; border-radius: 8px; }", ["CSS", "Flexbox", "Responsive"], "flex: 1 means grow and shrink equally."),
 Q(5, "CSS Grid Gallery", "hard", "HTML/CSS", "CSS Grid", "Build a photo gallery where items fill rows and auto-fit columns.", "Use grid-template-columns: repeat(auto-fill, minmax(...)) for responsive grid.", ".gallery { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 12px; }\n.gallery img { width: 100%; height: auto; }", ["CSS", "Grid", "Responsive"], "auto-fill packs as many columns as fit."),
 Q(6, "Sticky Header Navigation", "medium", "HTML/CSS", "Positioning", "Make a navigation bar stick to the top of the viewport when scrolling.", "Use position: sticky with top: 0 on the nav element.", "nav { position: sticky; top: 0; background: #fff; z-index: 100; padding: 12px; }", ["CSS", "Positioning", "sticky"], "sticky behaves like relative until it hits the top edge."),
 Q(7, "Two-Column Layout", "medium", "HTML/CSS", "Layout", "Create a two-column layout with a fixed-width sidebar and fluid main content.", "Use flex or grid with a fixed sidebar width and flex main area.", ".layout { display: flex; }\n.sidebar { width: 250px; }\n.main { flex: 1; padding: 24px; }", ["CSS", "Layout", "Flexbox"], "flex: 1 makes the main area fill remaining space."),
 Q(8, "Media Query Responsive Text", "medium", "HTML/CSS", "Responsive Design", "Adjust font sizes and layout for small screens using media queries.", "Define breakpoints and override sizes for smaller viewports.", "body { font-size: 16px; }\n@media (max-width: 768px) { body { font-size: 14px; } .col { flex-direction: column; } }", ["CSS", "Responsive", "Media Queries"], "Use max-width breakpoints to scale down."),
 Q(9, "Table Styling", "easy", "HTML/CSS", "Tables", "Style a data table with alternating row colors and hover effects.", "Use :nth-child(even) for stripes and :hover for highlight.", "table { border-collapse: collapse; width: 100%; }\ntd, th { padding: 10px; border: 1px solid #ddd; }\ntr:nth-child(even) { background: #f9f9f9; }\ntr:hover { background: #eee; }", ["CSS", "Tables", "Pseudo-classes"], "nth-child(even) selects even rows."),
 Q(10, "CSS Variable Theme Switcher", "hard", "HTML/CSS", "CSS Variables", "Define CSS custom properties and switch between light and dark themes by toggling a class.", "Store colors in :root variables and override them in a .dark class.", ":root { --bg: #fff; --text: #000; }\n.dark { --bg: #111; --text: #fff; }\nbody { background: var(--bg); color: var(--text); }", ["CSS", "Variables", "Theming"], "var() reads a custom property value.")
]
path = os.path.join(BASE, "htmlCssQuestions.js")
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(arr) + "\n")
print("wrote", len(arr), "questions to htmlCssQuestions.js")