# Regenerates reactQuestions.js with proper JSON formatting
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, category, topic, problem, approach, solution, concepts, hint, leetcode=None):
    return {"id":id,"title":title,"difficulty":difficulty,"category":category,"topic":topic,"problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":leetcode,"hint":hint}

arr = [
 Q(21, "Counter with useState", "easy", "React", "useState", "Build a counter component with increment, decrement, and reset buttons using React state.", "Use the useState hook to hold the count and update it via buttons.", "function Counter() {\n  const [n, setN] = useState(0);\n  return (\n    <div>\n      <p>{n}</p>\n      <button onClick={() => setN(n + 1)}>+</button>\n      <button onClick={() => setN(n - 1)}>-</button>\n      <button onClick={() => setN(0)}>Reset</button>\n    </div>\n  );\n}", ["useState", "Events", "JSX"], "Always use the setter function to update state."),
 Q(22, "Effect Counter", "medium", "React", "useEffect", "Update the document title to show the current count whenever it changes.", "Use useEffect with the count in its dependency array to set the title.", "useEffect(() => { document.title = \"Count: \" + n; }, [n]);", ["useEffect", "Side effects", "Dependencies"], "An empty dependency array runs the effect only on mount."),
 Q(23, "Props Greeting", "easy", "React", "Props", "Create a Greeting component that displays a personalized message passed via props.", "Accept a name prop and render it inside JSX.", "function Greeting({ name }) {\n  return <h1>Hello, {name}!</h1>;\n}\n<Greeting name=\"Alice\" />", ["Props", "Components", "JSX"], "Props flow from parent to child as read-only."),
 Q(24, "Conditional Rendering Banner", "easy", "React", "Conditional rendering", "Show a success or error message depending on a boolean state.", "Use an if/else or ternary inside JSX to choose what to render.", "function Banner() {\n  const [ok, setOk] = useState(true);\n  return ok ? <p>Success</p> : <p>Error</p>;\n}", ["Conditional", "useState", "JSX"], "Ternary is the most common inline conditional pattern."),
 Q(25, "Todo List with State", "medium", "React", "Lists", "Render a list of todo items from an array stored in state.", "Map over the array inside JSX to produce list items.", "function TodoList() {\n  const [tasks, setTasks] = useState([\"A\", \"B\"]);\n  return <ul>{tasks.map((t, i) => <li key={i}>{t}</li>)}</ul>;\n}", ["useState", "Lists", "key prop"], "Always provide a key prop when mapping to lists."),
 Q(26, "Controlled Form", "medium", "React", "Forms", "Create an input whose value is controlled by React state.", "Bind the input value to state and update state on change.", "function Form() {\n  const [v, setV] = useState(\"\");\n  return <input value={v} onChange={e => setV(e.target.value)} />;\n}", ["Controlled", "Forms", "useState"], "Controlled inputs must set value and onChange together."),
 Q(27, "Fetch Data from API", "hard", "React", "API fetching", "Load and display a list of posts from a public API using useEffect.", "Call fetch inside useEffect, update state with the response, and handle loading.", "useEffect(() => {\n  fetch(\"https://jsonplaceholder.typicode.com/posts\")\n    .then(r => r.json()).then(setPosts);\n}, []);", ["useEffect", "fetch", "Async"], "An empty dependency array fetches only once on mount."),
 Q(28, "Custom Hook useCounter", "hard", "React", "Custom hooks", "Extract counter logic into a reusable custom hook.", "Move state and handlers into a function starting with use and return them.", "function useCounter(initial = 0) {\n  const [n, setN] = useState(initial);\n  return { n, inc: () => setN(n + 1), dec: () => setN(n - 1) };\n}", ["Custom hooks", "Reuse", "useState"], "Hooks must be called in the same order every render."),
 Q(29, "Theme Toggle with Context", "hard", "React", "Component communication", "Share a theme between distant components without prop drilling.", "Create a context, provide a value, and consume it with useContext.", "const C = createContext();\nfunction Provider({ children }) {\n  const [dark, setDark] = useState(false);\n  return <C.Provider value={{ dark, setDark }}>{children}</C.Provider>;\n}", ["Context", "useContext", "Provider"], "Context is ideal for theme, user, and locale sharing."),
 Q(30, "Search Filter with Debounce", "hard", "React", "Events", "Delay a search query state update so API calls do not fire on every keystroke.", "Store the raw value in state but debounce the effect that uses it.", "useEffect(() => {\n  const t = setTimeout(() => search(query), 300);\n  return () => clearTimeout(t);\n}, [query]);", ["useEffect", "Debounce", "Cleanup"], "Return a cleanup function to cancel the previous timer.")
]
path = os.path.join(BASE, "reactQuestions.js")
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(arr) + "\n")
print("wrote", len(arr), "questions to reactQuestions.js")