# Writes Stack & Queue questions 151-160
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Stack & Queue","topic":"Stack & Queue","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(151, "Stack Push and Pop", "easy", "Implement a stack that supports push and pop operations.", "Use an array or ArrayList to store elements.", "import java.util.ArrayList;\npublic class Stack {\n    ArrayList<Integer> data = new ArrayList<>();\n    void push(int v) { data.add(v); }\n    int pop() { return data.remove(data.size() - 1); }\n    int peek() { return data.get(data.size() - 1); }\n    boolean empty() { return data.isEmpty(); }\n}", ["stack", "push", "pop"], "Pop removes the last added element."),
 Q(152, "Balanced Parentheses", "medium", "Check if a string of brackets is properly nested.", "Use a stack to match opening and closing brackets.", "import java.util.*;\npublic class Balance {\n    public static void main(String[] args) {\n        String s = \"()[]{}\";\n        Deque<Character> stack = new ArrayDeque<>();\n        for (char c : s.toCharArray()) {\n            if (c == '(' || c == '[' || c == '{') stack.push(c);\n            else {\n                if (stack.isEmpty()) { System.out.println(false); return; }\n                char top = stack.pop();\n                if ((c == ')' && top != '(') || (c == ']' && top != '[') || (c == '}' && top != '{')) { System.out.println(false); return; }\n            }\n        }\n        System.out.println(stack.isEmpty());\n    }\n}", ["stack", "parentheses", "balanced"], "Push opening brackets, pop to match closing ones."),
 Q(153, "Reverse a Stack", "medium", "Reverse the order of elements in a stack.", "Use recursion or an auxiliary stack.", "import java.util.*;\npublic class Reverse {\n    public static void main(String[] args) {\n        Deque<Integer> s = new ArrayDeque<>();\n        s.push(1); s.push(2); s.push(3);\n        Deque<Integer> aux = new ArrayDeque<>();\n        while (!s.isEmpty()) aux.push(s.pop());\n        while (!aux.isEmpty()) System.out.println(aux.pop());\n    }\n}", ["stack", "reverse", "auxiliary"], "Transfer to another stack to reverse order."),
 Q(154, "Min Stack", "hard", "Track the minimum element in a stack at all times.", "Keep a parallel stack of minimums.", "import java.util.*;\npublic class MinStack {\n    Deque<Integer> data = new ArrayDeque<>();\n    Deque<Integer> mins = new ArrayDeque<>();\n    void push(int v) {\n        data.push(v);\n        if (mins.isEmpty() || v <= mins.peek()) mins.push(v);\n    }\n    int pop() {\n        int v = data.pop();\n        if (!mins.isEmpty() && v == mins.peek()) mins.pop();\n        return v;\n    }\n    int getMin() { return mins.peek(); }\n}", ["stack", "minimum", "auxiliary"], "A second stack tracks the current minimum."),
 Q(155, "Next Greater Element", "hard", "For each element find the next element that is larger than it.", "Use a stack to defer processing of smaller elements.", "import java.util.*;\npublic class NGE {\n    public static void main(String[] args) {\n        int[] arr = {4, 5, 2, 25};\n        Deque<Integer> stack = new ArrayDeque<>();\n        for (int v : arr) {\n            while (!stack.isEmpty() && stack.peek() < v) System.out.println(stack.pop() + \" -> \" + v);\n            stack.push(v);\n        }\n    }\n}", ["stack", "next greater", "monotonic"], "Pop while the current value is greater than the top."),
 Q(156, "Evaluate Postfix Expression", "hard", "Compute the result of a postfix arithmetic expression.", "Push numbers and apply operators to popped values.", "import java.util.*;\npublic class Postfix {\n    public static void main(String[] args) {\n        String expr = \"2 3 5 * +\";\n        Deque<Integer> stack = new ArrayDeque<>();\n        for (String t : expr.split(\" \")) {\n            if (t.equals(\"+\")) stack.push(stack.pop() + stack.pop());\n            else if (t.equals(\"*\")) stack.push(stack.pop() * stack.pop());\n            else stack.push(Integer.parseInt(t));\n        }\n        System.out.println(stack.pop());\n    }\n}", ["stack", "postfix", "expression"], "Pop the right operand first, then the left."),
 Q(157, "Queue Using Stacks", "hard", "Implement a queue using only two stacks.", "Move elements between stacks on dequeue.", "import java.util.*;\npublic class MyQueue {\n    Deque<Integer> in = new ArrayDeque<>();\n    Deque<Integer> out = new ArrayDeque<>();\n    void enqueue(int v) { in.push(v); }\n    int dequeue() {\n        if (out.isEmpty()) while (!in.isEmpty()) out.push(in.pop());\n        return out.pop();\n    }\n}", ["queue", "stack", "two stacks"], "Lazy transfer from in-stack to out-stack."),
 Q(158, "Implement Circular Queue", "medium", "Build a circular queue that reuses freed space.", "Use an array with front and rear pointers.", "public class CircularQueue {\n    int[] data;\n    int front = 0, size = 0;\n    CircularQueue(int cap) { data = new int[cap]; }\n    void enqueue(int v) {\n        data[(front + size) % data.length] = v;\n        size++;\n    }\n    int dequeue() {\n        int v = data[front];\n        front = (front + 1) % data.length;\n        size--;\n        return v;\n    }\n}", ["queue", "circular", "array"], "Modulo arithmetic wraps the pointers around."),
 Q(159, "Priority Queue with Heap", "hard", "Insert elements and always remove the smallest one first.", "Store values in a binary heap array.", "import java.util.*;\npublic class PQ {\n    ArrayList<Integer> heap = new ArrayList<>();\n    void push(int v) {\n        heap.add(v);\n        int i = heap.size() - 1;\n        while (i > 0 && heap.get(i) < heap.get((i - 1) / 2)) {\n            Collections.swap(heap, i, (i - 1) / 2);\n            i = (i - 1) / 2;\n        }\n    }\n    int pop() {\n        int min = heap.get(0);\n        heap.set(0, heap.get(heap.size() - 1));\n        heap.remove(heap.size() - 1);\n        return min;\n    }\n}", ["heap", "priority queue", "min heap"], "Bubble up on insert to maintain heap order."),
 Q(160, "Sliding Window Maximum", "hard", "Find the maximum in every contiguous window of size k.", "Use a deque to track useful elements in decreasing order.", "import java.util.*;\npublic class WindowMax {\n    public static void main(String[] args) {\n        int[] arr = {1, 3, -1, -3, 5, 3, 6, 7};\n        int k = 3;\n        Deque<Integer> dq = new ArrayDeque<>();\n        for (int i = 0; i < arr.length; i++) {\n            while (!dq.isEmpty() && dq.peekFirst() < i - k + 1) dq.pollFirst();\n            while (!dq.isEmpty() && arr[dq.peekLast()] <= arr[i]) dq.pollLast();\n            dq.offerLast(i);\n            if (i >= k - 1) System.out.println(arr[dq.peekFirst()]);\n        }\n    }\n}", ["deque", "sliding window", "maximum"], "Keep the deque in decreasing value order.")
]
path = os.path.join(BASE, "stackQueueQuestions.js")
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(arr) + "\n")
print("wrote", len(arr), "questions to stackQueueQuestions.js")