# Writes Stack & Queue questions 161-170
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Stack & Queue","topic":"Stack & Queue","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(161, "Stack Using Queues", "hard", "Implement a stack using only two queues.", "Push to the second queue then move all elements over.", "import java.util.*;\npublic class MyStack {\n    Queue<Integer> q1 = new LinkedList<>();\n    Queue<Integer> q2 = new LinkedList<>();\n    void push(int v) {\n        q2.offer(v);\n        while (!q1.isEmpty()) q2.offer(q1.poll());\n        Queue<Integer> t = q1; q1 = q2; q2 = t;\n    }\n    int pop() { return q1.poll(); }\n}", ["stack", "queue", "two queues"], "Swap queues after each push to keep the top accessible."),
 Q(162, "Sort a Stack", "hard", "Sort a stack so the smallest element is on top.", "Use recursion or an auxiliary sorted stack.", "import java.util.*;\npublic class SortStack {\n    public static void main(String[] args) {\n        Deque<Integer> s = new ArrayDeque<>();\n        s.push(3); s.push(1); s.push(2);\n        Deque<Integer> aux = new ArrayDeque<>();\n        while (!s.isEmpty()) {\n            int temp = s.pop();\n            while (!aux.isEmpty() && aux.peek() > temp) s.push(aux.pop());\n            aux.push(temp);\n        }\n        while (!aux.isEmpty()) System.out.println(aux.pop());\n    }\n}", ["stack", "sorting", "auxiliary"], "Insert each element into the sorted auxiliary stack."),
 Q(163, "Queue Implementation with Array", "easy", "Implement a simple queue using a fixed-size array.", "Use front and rear pointers to track positions.", "public class Queue {\n    int[] data;\n    int front = 0, rear = 0, size = 0;\n    Queue(int cap) { data = new int[cap]; }\n    void enqueue(int v) { data[rear] = v; rear = (rear + 1) % data.length; size++; }\n    int dequeue() { int v = data[front]; front = (front + 1) % data.length; size--; return v; }\n}", ["queue", "array", "circular"], "Modulo arithmetic wraps the rear pointer."),
 Q(164, "Deque Implementation", "easy", "Implement a double-ended queue that allows add/remove at both ends.", "Maintain an array with two moving pointers.", "public class Deque {\n    int[] data;\n    int front = 0, size = 0;\n    Deque(int cap) { data = new int[cap]; }\n    void addFirst(int v) {\n        front = (front - 1 + data.length) % data.length;\n        data[front] = v;\n        size++;\n    }\n    void addLast(int v) {\n        data[(front + size) % data.length] = v;\n        size++;\n    }\n}", ["deque", "double ended", "array"], "Wrap the front pointer backwards with modulo."),
 Q(165, "First Non-Repeating Character in Stream", "hard", "Find the first character in a stream that appears only once so far.", "Use a queue and a frequency array.", "import java.util.*;\npublic class Stream {\n    public static void main(String[] args) {\n        String s = \"aabc\";\n        int[] freq = new int[256];\n        Queue<Character> q = new LinkedList<>();\n        for (char c : s.toCharArray()) {\n            freq[c]++;\n            q.offer(c);\n            while (!q.isEmpty() && freq[q.peek()] > 1) q.poll();\n            if (!q.isEmpty()) System.out.println(q.peek());\n        }\n    }\n}", ["queue", "stream", "frequency"], "Drop characters that have repeated from the front."),
 Q(166, "Next Smaller Element", "hard", "For each element find the next element that is smaller than it.", "Use a stack to defer processing of larger elements.", "import java.util.*;\npublic class NSE {\n    public static void main(String[] args) {\n        int[] arr = {4, 5, 2, 10};\n        Deque<Integer> stack = new ArrayDeque<>();\n        for (int v : arr) {\n            while (!stack.isEmpty() && stack.peek() > v) System.out.println(stack.pop() + \" -> \" + v);\n            stack.push(v);\n        }\n    }\n}", ["stack", "next smaller", "monotonic"], "Pop while the current value is smaller than the top."),
 Q(167, "Largest Rectangle in Histogram", "hard", "Find the largest rectangular area in a histogram.", "Use a stack to track increasing bar indices.", "import java.util.*;\npublic class Hist {\n    public static void main(String[] args) {\n        int[] h = {2, 1, 5, 6, 2, 3};\n        Deque<Integer> stack = new ArrayDeque<>();\n        int max = 0;\n        for (int i = 0; i <= h.length; i++) {\n            int cur = (i == h.length) ? 0 : h[i];\n            while (!stack.isEmpty() && cur < h[stack.peek()]) {\n                int height = h[stack.pop()];\n                int width = stack.isEmpty() ? i : i - stack.peek() - 1;\n                max = Math.max(max, height * width);\n            }\n            stack.push(i);\n        }\n        System.out.println(max);\n    }\n}", ["stack", "histogram", "area"], "Pop bars and compute area when a smaller bar appears."),
 Q(168, "Queue Reconstruction by Height", "hard", "Reconstruct a queue where each person counts how many taller people are in front.", "Sort by height then insert by count.", "import java.util.*;\npublic class Reconstruct {\n    public static void main(String[] args) {\n        int[][] people = {{7, 0}, {4, 4}, {7, 1}, {5, 0}, {6, 1}, {5, 2}};\n        Arrays.sort(people, (a, b) -> a[0] != b[0] ? b[0] - a[0] : a[1] - b[1]);\n        List<int[]> result = new ArrayList<>();\n        for (int[] p : people) result.add(p[1], p);\n        for (int[] p : result) System.out.println(p[0] + \" \" + p[1]);\n    }\n}", ["queue", "greedy", "reconstruction"], "Insert each person at their k index."),
 Q(169, "Implement Two Stacks in One Array", "hard", "Store two stacks inside a single array without collision.", "Grow one stack from the left and the other from the right.", "public class TwoStacks {\n    int[] data;\n    int left = -1, right;\n    TwoStacks(int cap) { data = new int[cap]; right = cap; }\n    void pushLeft(int v) { data[++left] = v; }\n    void pushRight(int v) { data[--right] = v; }\n    int popLeft() { return data[left--]; }\n    int popRight() { return data[right++]; }\n}", ["stack", "array", "two stacks"], "One stack grows forward, the other grows backward."),
 Q(170, "Generate Binary Numbers Using Queue", "easy", "Generate the first n binary numbers in increasing order.", "Use a queue starting from 1 and append 0 and 1.", "import java.util.*;\npublic class Binary {\n    public static void main(String[] args) {\n        Queue<String> q = new LinkedList<>();\n        q.offer(\"1\");\n        for (int i = 0; i < 5; i++) {\n            String s = q.poll();\n            System.out.println(s);\n            q.offer(s + \"0\");\n            q.offer(s + \"1\");\n        }\n    }\n}", ["queue", "binary", "bfs"], "Each binary number spawns two children by appending 0 and 1.")
]
path = os.path.join(BASE, "stackQueueQuestions.js")
with open(path, "r", encoding="utf-8") as f:
    content = f.read()
start = content.index("[")
end = content.rindex("]") + 1
existing = json.loads(content[start:end])
allq = existing + arr
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(allq) + "\n")
print("appended", len(arr), "to stackQueueQuestions.js, total", len(allq))