# Writes Strings questions 111-120
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Strings","topic":"Strings","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(111, "Reverse String", "easy", "Reverse a string and print the result.", "Build a new string by iterating from the end.", "public class Rev {\n    public static void main(String[] args) {\n        String s = \"hello\";\n        String r = \"\";\n        for (int i = s.length() - 1; i >= 0; i--) r += s.charAt(i);\n        System.out.println(r);\n    }\n}", ["strings", "loop", "reverse"], "charAt(i) returns the character at index i."),
 Q(112, "Palindrome Check", "easy", "Check whether a string reads the same forwards and backwards.", "Compare characters from both ends moving inward.", "public class Pal {\n    public static void main(String[] args) {\n        String s = \"level\";\n        boolean ok = true;\n        for (int i = 0; i < s.length() / 2; i++) {\n            if (s.charAt(i) != s.charAt(s.length() - 1 - i)) { ok = false; break; }\n        }\n        System.out.println(ok ? \"Palindrome\" : \"Not\");\n    }\n}", ["strings", "palindrome", "loop"], "Only iterate to the middle of the string."),
 Q(113, "Character Frequency", "easy", "Count how many times each character appears in a string.", "Use an array of size 256 to accumulate counts.", "public class Freq {\n    public static void main(String[] args) {\n        String s = \"hello\";\n        int[] counts = new int[256];\n        for (int i = 0; i < s.length(); i++) counts[s.charAt(i)]++;\n        for (int i = 0; i < 256; i++) if (counts[i] > 0) System.out.println((char) i + \" = \" + counts[i]);\n    }\n}", ["strings", "frequency", "array"], "The char value is used as an array index."),
 Q(114, "Anagram Check", "medium", "Check if two strings contain the same characters in any order.", "Compare sorted versions of both strings.", "import java.util.Arrays;\npublic class Ana {\n    public static void main(String[] args) {\n        String a = \"listen\", b = \"silent\";\n        char[] x = a.toCharArray();\n        char[] y = b.toCharArray();\n        Arrays.sort(x);\n        Arrays.sort(y);\n        System.out.println(Arrays.equals(x, y) ? \"Anagram\" : \"Not\");\n    }\n}", ["strings", "anagram", "sorting"], "Sorting both strings makes comparison easy."),
 Q(115, "Duplicate Characters", "medium", "Print all characters that appear more than once.", "Use a HashSet to track seen characters.", "import java.util.HashSet;\npublic class Dup {\n    public static void main(String[] args) {\n        String s = \"programming\";\n        HashSet<Character> seen = new HashSet<>();\n        HashSet<Character> dups = new HashSet<>();\n        for (char c : s.toCharArray()) {\n            if (seen.contains(c)) dups.add(c);\n            else seen.add(c);\n        }\n        System.out.println(dups);\n    }\n}", ["strings", "duplicate", "hashset"], "Track seen characters and detect repeats."),
 Q(116, "String Compression", "medium", "Compress a string by replacing repeated characters with a count.", "Count consecutive identical characters.", "public class Compress {\n    public static void main(String[] args) {\n        String s = \"aaabbcc\";\n        StringBuilder sb = new StringBuilder();\n        int count = 1;\n        for (int i = 1; i <= s.length(); i++) {\n            if (i < s.length() && s.charAt(i) == s.charAt(i - 1)) count++;\n            else { sb.append(s.charAt(i - 1)).append(count); count = 1; }\n        }\n        System.out.println(sb);\n    }\n}", ["strings", "compression", "stringbuilder"], "Append the character and its run length."),
 Q(117, "Longest Substring Without Repeating Characters", "hard", "Find the length of the longest substring with all unique characters.", "Use a sliding window with a HashSet.", "import java.util.HashSet;\npublic class Long {\n    public static void main(String[] args) {\n        String s = \"abcabcbb\";\n        int max = 0, l = 0;\n        HashSet<Character> set = new HashSet<>();\n        for (int r = 0; r < s.length(); r++) {\n            while (set.contains(s.charAt(r))) set.remove(s.charAt(l++));\n            set.add(s.charAt(r));\n            max = Math.max(max, r - l + 1);\n        }\n        System.out.println(max);\n    }\n}", ["strings", "sliding window", "substring"], "Shrink the left side until the character is unique again."),
 Q(118, "String Rotation Check", "medium", "Check if one string is a rotation of another.", "Concatenate the first string with itself and search.", "public class Rot {\n    public static void main(String[] args) {\n        String a = \"watermelon\", b = \"melonwater\";\n        System.out.println((a.length() == b.length() && (a + a).contains(b)) ? \"Rotation\" : \"Not\");\n    }\n}", ["strings", "rotation", "contains"], "A rotation is always a substring of the doubled string."),
 Q(119, "Count Words", "easy", "Count how many words are in a given sentence.", "Split the string by whitespace.", "public class Words {\n    public static void main(String[] args) {\n        String s = \"Java is fun\";\n        String[] parts = s.trim().split(\"\\\\s+\");\n        System.out.println(parts.length);\n    }\n}", ["strings", "split", "words"], "split with a regular expression for whitespace."),
 Q(120, "Substring Search", "medium", "Find the first index where one string appears inside another.", "Use indexOf or a manual search.", "public class Sub {\n    public static void main(String[] args) {\n        String s = \"hello world\";\n        System.out.println(s.indexOf(\"world\"));\n    }\n}", ["strings", "substring", "search"], "indexOf returns -1 when the substring is missing.")
]
path = os.path.join(BASE, "stringQuestions.js")
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(arr) + "\n")
print("wrote", len(arr), "questions to stringQuestions.js")