# Writes Strings questions 121-130
import os, json
BASE = r"C:\Users\navry\OneDrive - hiet.org\Desktop\javapath-core-java_with_AI_Vr.12.5_YT\javapath-react\src\data"

def Q(id, title, difficulty, problem, approach, solution, concepts, hint):
    return {"id":id,"title":title,"difficulty":difficulty,"category":"Strings","topic":"Strings","problem":problem,"example":{"input":"See problem","output":"See problem"},"approach":approach,"solution":solution,"time":"O(1)","space":"O(1)","concepts":concepts,"leetcode":None,"hint":hint}

arr = [
 Q(121, "Longest Palindrome Substring", "hard", "Find the longest substring that is a palindrome.", "Expand around each possible center.", "public class LongPal {\n    public static void main(String[] args) {\n        String s = \"babad\";\n        String max = \"\";\n        for (int i = 0; i < s.length(); i++) {\n            String a = expand(s, i, i);\n            String b = expand(s, i, i + 1);\n            if (a.length() > max.length()) max = a;\n            if (b.length() > max.length()) max = b;\n        }\n        System.out.println(max);\n    }\n    static String expand(String s, int l, int r) {\n        while (l >= 0 && r < s.length() && s.charAt(l) == s.charAt(r)) { l--; r++; }\n        return s.substring(l + 1, r);\n    }\n}", ["strings", "palindrome", "expand"], "Each character can be the center of a palindrome."),
 Q(122, "String to Integer", "medium", "Convert a numeric string into an integer manually.", "Multiply the running total by 10 and add each digit.", "public class Atoi {\n    public static void main(String[] args) {\n        String s = \"1234\";\n        int n = 0;\n        for (int i = 0; i < s.length(); i++) n = n * 10 + (s.charAt(i) - '0');\n        System.out.println(n);\n    }\n}", ["strings", "parsing", "integer"], "Subtracting '0' converts a digit char to its numeric value."),
 Q(123, "Remove Vowels", "easy", "Remove all vowels from a string and print the result.", "Build a new string skipping vowel characters.", "public class NoVowels {\n    public static void main(String[] args) {\n        String s = \"hello world\";\n        StringBuilder sb = new StringBuilder();\n        for (char c : s.toCharArray()) if (\"aeiouAEIOU\".indexOf(c) < 0) sb.append(c);\n        System.out.println(sb);\n    }\n}", ["strings", "filter", "vowels"], "Use StringBuilder to build the result efficiently."),
 Q(124, "First Non-Repeating Character", "hard", "Find the first character that appears exactly once.", "Count frequencies then scan in original order.", "public class FirstUnique {\n    public static void main(String[] args) {\n        String s = \"swiss\";\n        int[] counts = new int[256];\n        for (char c : s.toCharArray()) counts[c]++;\n        for (char c : s.toCharArray()) if (counts[c] == 1) { System.out.println(c); break; }\n    }\n}", ["strings", "frequency", "unique"], "Two passes: count, then find the first with count one."),
 Q(125, "String Multiplication", "hard", "Multiply a numeric string by an integer and return the result.", "Perform digit-by-digit multiplication with carry.", "public class Multiply {\n    public static void main(String[] args) {\n        String s = \"123\";\n        int n = 4;\n        int carry = 0;\n        StringBuilder sb = new StringBuilder();\n        for (int i = s.length() - 1; i >= 0; i--) {\n            int prod = (s.charAt(i) - '0') * n + carry;\n            sb.append(prod % 10);\n            carry = prod / 10;\n        }\n        while (carry > 0) { sb.append(carry % 10); carry /= 10; }\n        System.out.println(sb.reverse());\n    }\n}", ["strings", "math", "multiplication"], "Process digits from right to left like pencil math."),
 Q(126, "Group Anagrams", "hard", "Group strings that are anagrams of each other together.", "Use a sorted key to group strings in a HashMap.", "import java.util.*;\npublic class Group {\n    public static void main(String[] args) {\n        String[] words = {\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"};\n        Map<String, List<String>> map = new HashMap<>();\n        for (String w : words) {\n            char[] chars = w.toCharArray();\n            Arrays.sort(chars);\n            String key = new String(chars);\n            map.computeIfAbsent(key, k -> new ArrayList<>()).add(w);\n        }\n        System.out.println(map.values());\n    }\n}", ["strings", "anagram", "hashmap"], "Sorted characters form a canonical key for anagrams."),
 Q(127, "String Matching Rabin-Karp", "hard", "Find all occurrences of a pattern in a text using hashing.", "Use a rolling hash to compare substrings quickly.", "public class RabinKarp {\n    public static void main(String[] args) {\n        String text = \"abracadabra\";\n        String pat = \"cad\";\n        for (int i = 0; i <= text.length() - pat.length(); i++) {\n            if (text.substring(i, i + pat.length()).equals(pat)) System.out.println(i);\n        }\n    }\n}", ["strings", "pattern matching", "hash"], "A rolling hash avoids comparing every substring."),
 Q(128, "Text Justification", "hard", "Format words into lines with maximum width and even spacing.", "Greedy pack words then add spaces between them.", "public class Justify {\n    public static void main(String[] args) {\n        String[] words = {\"This\", \"is\", \"an\", \"example\"};\n        int max = 16;\n        StringBuilder line = new StringBuilder();\n        int len = 0;\n        for (String w : words) {\n            if (len + w.length() > max) { System.out.println(line); line = new StringBuilder(); len = 0; }\n            if (line.length() > 0) line.append(\" \");\n            line.append(w);\n            len += w.length();\n        }\n        System.out.println(line);\n    }\n}", ["strings", "greedy", "formatting"], "Pack as many words as fit per line."),
 Q(129, "Valid Parentheses", "hard", "Check if a string of brackets is properly nested and matched.", "Use a stack to match opening and closing brackets.", "import java.util.*;\npublic class Valid {\n    public static void main(String[] args) {\n        String s = \"()[]{}\";\n        Deque<Character> stack = new ArrayDeque<>();\n        for (char c : s.toCharArray()) {\n            if (c == '(' || c == '[' || c == '{') stack.push(c);\n            else {\n                if (stack.isEmpty()) { System.out.println(false); return; }\n                char top = stack.pop();\n                if ((c == ')' && top != '(') || (c == ']' && top != '[') || (c == '}' && top != '{') { System.out.println(false); return; }\n            }\n        }\n        System.out.println(stack.isEmpty());\n    }\n}", ["strings", "stack", "parentheses"], "Push opening brackets and pop to match closing ones."),
 Q(130, "Longest Common Prefix", "easy", "Find the longest common prefix shared by all strings in an array.", "Compare characters column by column.", "public class Prefix {\n    public static void main(String[] args) {\n        String[] strs = {\"flower\", \"flow\", \"flight\"};\n        String result = \"\";\n        if (strs.length == 0) result = \"\";\n        else {\n            int i = 0;\n            while (i < strs[0].length()) {\n                char c = strs[0].charAt(i);\n                boolean match = true;\n                for (int j = 1; j < strs.length; j++) {\n                    if (i >= strs[j].length() || strs[j].charAt(i) != c) { match = false; break; }\n                }\n                if (!match) break;\n                i++;\n            }\n            result = strs[0].substring(0, i);\n        }\n        System.out.println(result);\n    }\n}", ["strings", "prefix", "comparison"], "Stop at the first mismatched character.")
]
path = os.path.join(BASE, "stringQuestions.js")
with open(path, "r", encoding="utf-8") as f:
    content = f.read()
start = content.index("[")
end = content.rindex("]") + 1
existing = json.loads(content[start:end])
allq = existing + arr
with open(path, "w", encoding="utf-8") as f:
    f.write("export default " + json.dumps(allq) + "\n")
print("appended", len(arr), "to stringQuestions.js, total", len(allq))